### ISSUE TITLE
Duplicate test suites appear in report when incorrect wildcard is used in Teamcity plugin

### ISSUE THREAD

**Issue by vania-pooh** [allure-framework/allure-core#337]
In Teamcity \ Jenkins \ Bamboo plugins we're using DirectoryScanner class with Ant globs to generate a list of input directories for Allure Report Builder which in its turn delegates report generation to AllureReportGenerator. If we specify ** as glob we can get a list of directories like that: **parent**, **parent/child**. In that case XML files are read two times and the same suite appears two times in report.

**Comment by baev** [comment]
We are going to remove directory scanner logic from generation tools (Maven, CLI, TeamCity already done, Jenkins and Bamboo is coming soon)
