### ISSUE TITLE
Add capability to preprocess @Issue string value

### ISSUE THREAD

**Issue by vania-pooh** [allure-framework/allure-core#363]
This is the second part of @Issue annotation support. Here we need to provide some way to preprocess string value coming from this annotation. #360 supports only 1 issue tracker out of the box. With this feature anyone could e.g. use annotations like that:
```java
@Issue("jira: EXAMPLE-1")
```
The value of the annotation could be parsed with issue preprocessor and could be converted e.g. to http://myjira.com/EXAMPLE-1

Built-in default implementation should do no preprocessing. I would propose to use the following interface:
```java
public interface IssuePreprocessor {

    // This pair contains absolute issue URL and human-readable title
    Pair<String, String> preprocess(String issueValue);

}
```

**Comment by baev** [comment]
You can use the custom prepare plugin for this:

```java
public class ProcessIssuePlugin implements PreparePlugin<AllureTestCase> {

    @Override
    public void prepare(AllureTestCase data) {
        for (Issue issue : data.getIssues()) {
            // do staff you need, an example:
            // issue.setName("blalala");
            // issue.setUrl("something");
        }
    }

    @Override
    public Class<AllureTestCase> getType() {
        return AllureTestCase.class;
    }
}
```
