### ISSUE TITLE
Format step titles with template engine [optionally]

### ISSUE THREAD

**Issue by lanwen** [allure-framework/allure-core#387]
The main idea: provide plugin system to override step title generation process.

Interface: `formatTitle(String annotationValue, Object[] args)`
annotation value is method name by default.

Then use formatter: https://github.com/jknack/handlebars.java or http://velocity.apache.org/engine/devel/index.html or `Formatter` by default.

Then you can specify class in allure.properties to use as formatter.

It can be used to format templates as `("Getting value {{meta.userInfo}}", meta)`

**Comment by baev** [comment]
Allure Report 2 has no titles, you can make your own plugin and change names as you wish
