### ISSUE TITLE
mvn site fails  [Can't find any results directories by pattern]

### ISSUE THREAD

**Issue by p00j4** [allure-framework/allure-core#391]
On 'mvn site' it fails with below error, 
but I can see allure-results folder got generated in target 
![screen shot 2014-09-25 at 4 05 29 pm](https://cloud.githubusercontent.com/assets/6470509/4403220/fcc23212-449f-11e4-85c3-f6921109402b.png)

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project PROJECT: Error during page generation: Error rendering Maven report: Can't find any results directories by pattern [target/allure] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

And on X switch

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project PROJECT: Error during page generation: Error rendering Maven report: Can't find any results directories by pattern [target/allure] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException:

```
 Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project PROJECT: Error during page generation
```

```
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
```

Caused by: org.apache.maven.plugin.MojoExecutionException: Error during page generation`
`Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error rendering Maven report: `

`Can't find any results directories by pattern [target/allure]`

`Caused by: org.apache.maven.reporting.MavenReportException: Can't find any results directories by pattern [target/allure]`

**Comment by deepakaravind** [comment]
Am getting the same error, where can I find the path to be updated properly? for the allure-results

**Comment by baev** [comment]
@deepakaravind see http://wiki.qatools.ru/display/AL/Allure+Maven+Plugin

**Comment by deepakaravind** [comment]
@baev Thanks Dmitiry for your response.  I did find the file and update it properly - but looks like some other issue which am trying to figure out.  Thanks anyways for you response :)
