### ISSUE TITLE
Difference between two reports (or timeline of changes between lot of reports)

### ISSUE THREAD

**Issue by lanwen** [allure-framework/allure-core#395]
Need to see:
- what was added
- what was removed
- which cases changes status
- which cases still broken, or failed

this feature will be useful to show managers dynamic of automation tests project

**Comment by arpitgold** [comment]
Nice feature... It will be very useful for everyone. :+1: 
It is a much awaiting feature for me. Hope it will be available soon.

**Comment by eroshenkoam** [comment]
Will be implements into TMS :)

**Comment by dsafar** [comment]
This would be great -- on a day-to-day basis being able to see which failures are new would help a lot with debugging, identifying product bugs, and determining which test cases failed due to legitimate product changes and need updating.

**Comment by vania-pooh** [comment]
@dsafar we'll opensource a related product during next months.

**Comment by baev** [comment]
> we'll opensource a related product during next months.

**Comment by arpitgold** [comment]
Can you please close this issue, when this functionality will be available?
It show wrong interpretation that this feature is completed.
Also you have any rough timelines, when will be that feature available.

**Comment by baev** [comment]
@arpitgold this functionality will not be available in allure framework. As we say before *we'll opensource a related product during next months*. And **related** not means that our new product will create difference between reports. So the issue closed as **should not be resolved**.
