### ISSUE TITLE
Attach screensot for testng report ?

### ISSUE THREAD

**Issue by tlytvyn** [allure-framework/allure-core#426]
Can you describe full phase of attaching screenshot to testng report ?
I am trying with listeners and also jsut simply calling attachement annotated method from test and nothing is attached still. Thank you

**Comment by vertissachin** [comment]
Hi ,

i am trying to attach a file to allure report using @attachment and i have called that methode from @aftermethode of testng, but while attaching a files, the methode A file goes to B and B's file to C method. and C methode file is missed. there is not file attached to the methode A.

i am using latest allure plugin version and testng adapter version.

please let us know if there is any solution to resolve it.


Thanks,
Sachin

**Comment by sskorol** [comment]
@vertissachin I believe you can't do that within `@AfterMethod` scope. Use listeners instead to catch `afterInvocation` event.
