### ISSUE TITLE
Incorrect displaying of exceptions in report if exceptions are thrown from steps and then catched 

### ISSUE THREAD

**Issue by alkedr** [allure-framework/allure-core#431]
See description of pull request #352 for complete example.
This is unrelated to multiple failures per testcase.

Catching exceptions is useful and sometimes unavoidable. For example JUnit rules always catch and rethrow all exceptions.

Scenario that triggers incorrect behavior:
1. Step1 is called
2. Step1 calls Step2
3. Step2 throws exception1
4. Step1 catches exception1
5. Somewhere else exception2 is thrown and not catched

In report exception2 will be displayed as thrown from Step2.

There can be different variations:
1. Step1 can be simple method (not step)
2. exception2 can be thrown from step or simple method

**Comment by eroshenkoam** [comment]
В общем, не надо так делать. 
Это противоречит нашей концепции построения отчета. 
Не лови эксепшены и все будет хорошо.
