### ISSUE TITLE
Truncated name of test

### ISSUE THREAD

**Issue by ASarco** [allure-framework/allure-core#442]
There is a small bug when generating the reports.

My tests use JunitParams because I need to run the same test over many different instruments, which I pass the name (in the form "IX.D.FTSE.DAILY.IP") to the test as parameter. This works very well in Eclipse, I can see the result of every test with the name of the instrument:

![allure1](https://cloud.githubusercontent.com/assets/9863532/5124097/2243a886-70ab-11e4-9fcf-feac18c4f0dd.png)

This also looks fine in the XML generated by Allure:

![allure2](https://cloud.githubusercontent.com/assets/9863532/5124105/368d5396-70ab-11e4-88c8-a7861f959f30.png)

However, on the final report, the name of the instrument is gone, only the last part after the last dot is shown (which in our case is not very useful because all of our instruments end with .IP):

![allure3](https://cloud.githubusercontent.com/assets/9863532/5124113/450fee7e-70ab-11e4-8d6e-c14995211188.png)

**Comment by clicman** [comment]
@baev will it be fixed in Allure? Faced same problem.

**Comment by paulakimenko** [comment]
Hi! I have the same issue.

Use : 
- Java
- Allure TestNG adaptor
- Maven

Example :
  Step Name : 
    Input : "open -> http://example.com/"
    Output : "Com/"

I tried to find reason of this and found this : 
Method : ru.yandex.qatools.allure.data.utils.TextUtils::simplify()
Input : "open -> http://example.com/"
Output : "com/"

**Comment by baev** [comment]
fixed in Allure 2
