### ISSUE TITLE
Add cucumber-jvm adaptor

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-core#464]
It will be good to allure will support cucumber-jvm framework via adaptor.

**Comment by clicman** [comment]
Finally I have created adaptor and an example project:
https://github.com/clicman/allure-cucumber-jvm-adaptor
https://github.com/clicman/allure-cucumber-jvm-example

**Comment by clicman** [comment]
Attachments fixed. Tests updated.

**Comment by vania-pooh** [comment]
@clicman thank you for contribution. Added you to the JVM teams in Allure Framework and Allure Examples projects. Please transfer allure-cucumber-jvm-adaptor to Allure Framework and example project to Allure Examples. Then I will add repositories to the team you were invited. Just took a quick look at the example and I would translate some russian comments in example steps to English.

**Comment by clicman** [comment]
@vania-pooh  I can not translate repositories. Faced permission issue.

>You don't have admin rights to allure-framework
>You don't have admin rights to allure-examples

**Comment by vania-pooh** [comment]
Then please just push to the following repositories:
https://github.com/allure-examples/allure-cucumber-jvm-example
https://github.com/allure-framework/allure-cucumber-jvm-adaptor
You should have enough rights to do so.
