### ISSUE TITLE
Missing Test Cases for  Some Tests - Allure Test Report

### ISSUE THREAD

**Issue by raj84** [allure-framework/allure-core#466]
I am using nunitadapter to generate the xml output. Then using the Allure Jenkins plugin to generate the report. The report is generated (report version 1.4.5). All tests are displayed.

For some tests, a couple of test cases are missing.

In Jenkins, if I navigate to the TestResults folder for the build, I am able to see all the test cases listed for a particular test (a total of 8 test cases). In Allure for the same test, I am able to see only 2 test cases.

This issue is happening across multiple tests. Jenkins Test Results folder is saying that there are a total of 266 test cases. Allure report says a total of 241 test cases.

**Comment by vania-pooh** [comment]
@raj84 could you please specify what could be the difference between present and missing test cases (e.g. different naming convention, attributes, location and so on)? Or you could provide an example project.

**Comment by vania-pooh** [comment]
Summon @ilya-murzinov.

**Comment by raj84** [comment]
@vania-pooh - Thanks for the quick response. Here are the details:

This is the Jenkins generated xml output for a test that has 8 test cases.

<?xml version='1.0' encoding='UTF-8'?>
<result plugin="junit@1.2-beta-4">
<suite>
      <file>c:\hudson\jobs\TrendChart-hackathon-smokeTest\workspace\temporary-junit-reports\TEST-XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest_32.xml</file>
      <name>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</name>
      <duration>14.836</duration>
      <cases>
        <case>
          <duration>0.002</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>AptBaseMixableTest.TestHasNUnitCategory</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>13.439</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>TestReadAverageLine</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>0.315</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>TestReadChart</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>0.238</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>TestReadPrePeriodTrendLine</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>0.215</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>TestReadRegressionLinePostOnly</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>0.227</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>TestReadTrendLine</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>0.229</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>TestReadRegressionLine(True)</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>0.171</duration>
          <className>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</className>
          <testName>TestReadRegressionLine(False)</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
      </cases>
    </suite>
	  <duration>23.649</duration>
  <keepLongStdio>true</keepLongStdio>
</result>


This is the Allure generated xml output for the same test where 6 test cases are missing


<?xml version="1.0"?>
<test-suite xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" start="1420725335039" stop="1420725353699" version="1.4.0" xmlns="urn:model.allure.qatools.yandex.ru">
  <name xmlns="">XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest</name>
  <test-cases xmlns="">
    <test-case start="1420725337469" stop="1420725337473" status="passed">
      <name>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest.AptBaseMixableTest.TestHasNUnitCategory</name>
    </test-case>
    <test-case start="1420725337475" stop="1420725351417" status="passed">
      <name>XXXXXXXXXXXXXXXXXXXX.Web.Tests.TrendChartLineProviderTest.TestReadAverageLine</name>
    </test-case>
  </test-cases>
</test-suite>

**Comment by raj84** [comment]
@vania-pooh I attached screenshots so that it is helpful instead of copy pasting text. Thanks for looking into it.

**Comment by raj84** [comment]
One more issue:

Also, I intentionally failed a test and other test hit an error.

![screenshot_010815_081847_pm](https://cloud.githubusercontent.com/assets/10454749/5674121/8d831fd4-9773-11e4-97dd-93738d68d6d1.jpg)


Allure Test Report doesnt track these tests.

![screenshot_010815_082240_pm](https://cloud.githubusercontent.com/assets/10454749/5674166/18a0b388-9774-11e4-8427-47e90e1e4c62.jpg)

**Comment by vania-pooh** [comment]
@raj84 all these issues should relate to NUnit adapter. I'm in fact neither an adapter developer nor C# programmer. So I just summoned the real adapter developer. Hope it helps you soon. Btw, this adapter is not widely used so it can contain bugs.

**Comment by raj84** [comment]
Thanks @vania-pooh 

I will wait for the adapter developer to respond. I really liked the allure test report and this issue prevents us from using it across multiple teams. Any help as soon as possible is much appreciated.

If you need any additional information, let me know.

**Comment by ilya-murzinov** [comment]
@vania-pooh, @raj84, I've created the [issue](https://github.com/allure-framework/allure-nunit/issues/9) in adapter project. Will investigate it ASAP.
