### ISSUE TITLE
What th meaning of "Duration" field in xUnit tab?

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-core#467]
As I can see in example [report](http://teamcity.qatools.ru/repository/download/allure_core_master_release/lastSuccessful/index.html?guest=1#/home) duration is test-after-test incremented time (next duration = all previous tests xexution times plus current) but I suppose it should be durarion for each test only. 
Is this feature or bug? If it it feature, could you explain use cases?

**Comment by vania-pooh** [comment]
@clicman this is probably because we're using manually created XML files for that. I would say this is caused by copy-paste in XML [files](https://github.com/allure-framework/allure-core/tree/master/allure-model/src/test/resources/allure-results).

**Comment by vania-pooh** [comment]
@clicman please reopen if you consider that an issue. You could send a PR with more random start and stop timestamps to allure-core as well.

**Comment by clicman** [comment]
Could not reopen, but it is not copy-paste. There is a link to archive [link](https://www.dropbox.com/s/bp3qijcjjwdmy0v/allure-results.zip?dl=0). All of steps are sleep for 5 seconds and it is easy to calculate that problem exists.

**Comment by vania-pooh** [comment]
@baev thoughts?

**Comment by baev** [comment]
@clicman I see the problem. What version of maven surefire plugin are you using?

**Comment by clicman** [comment]
2.18

**Comment by baev** [comment]
try to use 2.17 or less

**Comment by baev** [comment]
problem in the following lines:
https://github.com/allure-framework/allure-core/blob/master/allure-junit-adaptor/src/main/java/ru/yandex/qatools/allure/junit/AllureRunListener.java#L42-L44

**Comment by clicman** [comment]
@baev 
>try to use 2.17 or less
I can`t. I need a parent description on testRun started


And it really fixes the problem? I was initially removed this code from cucumber-jvm adaptor, but bug here. Okay, I will try to investigate problem as soon as i have time.

**Comment by clicman** [comment]
Commented related PR.
