### ISSUE TITLE
Generating of report has crash if XML contains wrong symbols

### ISSUE THREAD

**Issue by ko4evnik** [allure-framework/allure-core#468]
If even one xml contains wrong symbols generating of report is stopped.
Two moments:
1. The fact of crash
2. Report should be generate independently of broken xml file.

Bad XML: https://drive.google.com/file/d/0B7cU5hwdvThsLXV3VGVaZ3JCeWM/view?usp=sharing
Stacktrace:
$ /usr/local/allure-cli/bin/allure generate /tmp/111/ -v 1.4.5 -o /tmp/222/temp
Error
  com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2
  of 2-byte UTF-8 sequence.
java.lang.reflect.InvocationTargetException

**Comment by baev** [comment]
Thanks for feedback!

We have **validateXML** property in report generator but...it cannot be used in the current solution - [report builder](https://github.com/allure-framework/allure-report-builder) doesn't support this property yet.

Right now we working on new version of allure - data generation module refactoring it's main issue of this version, so I think we solve this issue

**Comment by baev** [comment]
Your issue in report builder - https://github.com/allure-framework/allure-report-builder/issues/1
