### ISSUE TITLE
Tree structure for allure.environment

### ISSUE THREAD

**Issue by pupssman** [allure-framework/allure-core#469]
We have a plenty of properties in our ``allure.environment`` that are related to different entities.
It would be great to display them in the report in a tree-like structure.

Simple solution could be splitting existing properties' name by the dot and creating a nested structure with that. 

It would work nicely for cases similar to presented in the figure:
![nested_env](https://cloud.githubusercontent.com/assets/2619359/5857875/f3fcd222-a25f-11e4-84fd-18b8046b1e74.png)

What do you think, @just-boris ?

**Comment by just-boris** [comment]
Make when I find time for it.
Hope I will be in this mounth

**Comment by pupssman** [comment]
So, any hope on this?

**Comment by baev** [comment]
@pupssman now we working on new overview tab - now it is will be some set of widgets and also we are going to create new tab with environment.

**Comment by pupssman** [comment]
@baev, great! Have you got any ideas on when it will be ready?

**Comment by baev** [comment]
Nope =(

**Comment by baev** [comment]
I don't know how it should be done in common case. IMHO sorted list is more useful. BTW it can be done via custom plugin in Allure 2
