### ISSUE TITLE
TMS ID annotation

### ISSUE THREAD

**Issue by pozharko** [allure-framework/allure-core#470]
TMS links are implemented, but there is no annotation for this links. It would be cool to have one.

**Comment by vania-pooh** [comment]
Agreed.

**Comment by volkovs** [comment]
Could it be @ TestId ?

**Comment by baev** [comment]
@volkovs we propose `@TestCaseId`

**Comment by volkovs** [comment]
@baev That annotation is on method level only, isn't it?
Then I can add it tonight.

**Comment by baev** [comment]
> That annotation is on method level only, isn't it?

Yep, method level only

**Comment by baev** [comment]
closed via #472

**Comment by serhatbolsu** [comment]
I could not make this to work with 1.4.6 I have allure-properties file in project. Also allure.issues.tracker.pattern does not work. Is there a way I provide this with maven ? 
thank you

**Comment by pozharko** [comment]
Thank you!
