### ISSUE TITLE
Generating reports in Cucumber is too long

### ISSUE THREAD

**Issue by gabyshev** [allure-framework/allure-core#473]
```bundle exec cucumber features``` takes 35m26.729s

And if I run the same tests wit Allure formatter
```bundle exec cucumber features -f AllureCucumber::Formatter```
real	676m5.260s
user	3m3.384s
sys	3m7.436s

This is the console output

    17:34:26 Starting case_or_suite Публичная часть. Поиск. Новый дизайн with labels {:severity=>:normal}
    17:34:26 Starting test Публичная часть. 
      # a lot of information from Allure formatter
    04:46:08 Stopping case_or_suite Публичная часть. Поиск. Новый дизайн
    04:46:08 Writing file 'gen/allure-results/a824fa50-87d2-0132-ffc1-02deadbeef05-testsuite.xml'...
    04:46:09 Build step 'Execute shell' marked build as failure
    04:46:09 Allure Report Generation: started
    04:46:09 Allure Report Generation: find directories by mask [**/allure-results]
    04:46:09 Allure Report Generation: found allure result directories [/var/jenkins/workspace/autotests-RealtyAutotests/gen/allure-results]
    04:46:09 Allure Report Generation: copy founded directories in directory [/var/jenkins/workspace/autotests-RealtyAutotests/allure6222696439890247726.tmp/results]
    04:46:09 Allure Report Generation: generate report from directory [/var/jenkins/workspace/autotests-RealtyAutotests/allure6222696439890247726.tmp]
    04:46:09 Allure Report Generation: proxy settings [active:'false', host:'null', port:'0', username:'null', password: '']
    04:46:29 Allure Report Generation: attach report link to build and project
    04:46:30 Allure Report Generation: completed

Any suggestions why it takes so long from execution?

**Comment by baev** [comment]
@gabyshev report generation takes 21s. Seems like its [cucumberJVM](https://github.com/allure-framework/allure-cucumber-jvm-adaptor) issue.

**Comment by gabyshev** [comment]
@baev sorry issue was on our side. Closing
