### ISSUE TITLE
Hide long messages of exceptions on defects, overview and testсase tabs

### ISSUE THREAD

**Issue by Kuhtich** [allure-framework/allure-core#483]
See expamples:
1) Defectes
![1 1](https://cloud.githubusercontent.com/assets/2588553/6102921/ee9a8034-b04e-11e4-9430-162702a4b340.png)
![1 2](https://cloud.githubusercontent.com/assets/2588553/6102920/ee98eaf8-b04e-11e4-833d-d9a87665fd94.png)
2) Defects tab, unhide message on click:
![2 1](https://cloud.githubusercontent.com/assets/2588553/6102924/ee9c3bcc-b04e-11e4-9074-3cb9e05e5e4e.png)
![2 2](https://cloud.githubusercontent.com/assets/2588553/6102922/ee9c2984-b04e-11e4-92e5-09f9d427f1b4.png)
3) Overview tab
![3 1](https://cloud.githubusercontent.com/assets/2588553/6102923/ee9c4fea-b04e-11e4-8d0b-66ce726b311f.png)
![3 2](https://cloud.githubusercontent.com/assets/2588553/6102925/ee9eccde-b04e-11e4-8252-a14658851d56.png)

**Comment by just-boris** [comment]
related https://github.com/allure-framework/allure-core/pull/479, but I'm not sure that it should be fixed in allure, maybe in tests

**Comment by baev** [comment]
@Kuhtich I don't know how to solve it in general way. Lets create a new tab plugin (I can help you) with nice messages trimming for your case.

**Comment by baev** [comment]
should be done via custom plugin
