### ISSUE TITLE
1.4.7 Overview Failed status even if all tests passed

### ISSUE THREAD

**Issue by volkovs** [allure-framework/allure-core#488]
Please see the difference
1.4.7:
![image](https://cloud.githubusercontent.com/assets/743546/6190339/d18c022a-b3a9-11e4-809e-310414a7a181.png)

1.4.5
![image](https://cloud.githubusercontent.com/assets/743546/6190361/f1e2e5f2-b3a9-11e4-93ff-3d1be9203d08.png)

I guess Defects page doesn't show funny picture (No defects) exactly by the same reason.

**Comment by baev** [comment]
Thanks for suggestion

I mark 1.4.7 as pre-release (An example you can find reference to non-existing pony at https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.7). 

I guess we release 1.4.8 with bug fixes in few days

**Comment by baev** [comment]
fixed via #490
