### ISSUE TITLE
Text attachments are getting downloaded when opened instead of displayed on the screen

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-core#500]
I have next method that stores log file into allure report : 
```java
@Attachment(value = "{0}", type = "text")
	private String writeAllureLogFile(String fileName, File file){
		if (file != null){
			BufferedReader reader = null; 
			try {
				reader = new BufferedReader( new FileReader(file));
			}catch (FileNotFoundException e){
				write(Command.ERROR, String.format("%s file was not found", file));
			}
			String         line = null;
			StringBuilder  stringBuilder = new StringBuilder();
			String         ls = System.getProperty("line.separator");

			try {
				while( ( line = reader.readLine() ) != null ) {
					stringBuilder.append( line );
					stringBuilder.append( ls );
				}
			}catch (IOException e){
				write(Command.ERROR, "IO Exception appeared : \n "+e.getStackTrace());
			}
			return stringBuilder.toString();	
		} else {
			return null ;
		}
		
	}
```

When i click on image screenshot - it's getting displayed properly in browser, but when i try to read text file( with *.log extension or *.xml extension) , then it's just get's downloaded by the browser. Tried in Chrome and Firefox - in both it's get downloaded. I would like to display content of this text files in the browser - how can i achieve that ?

**Comment by baev** [comment]
@azakordonets you should specify correct mime-type for attachment. An example for text you should specify `text/plain`.

**Comment by azakordonets** [comment]
Thanks for so fast reply - it worked !
