### ISSUE TITLE
Incorrect report test name after upgrading to 1.4.10 (from 1.4.8).

### ISSUE THREAD

**Issue by LooMaclin** [allure-framework/allure-core#510]
Incorrect report test name after upgrading to 1.4.10 (from 1.4.8).
See the screenshot.
![1](https://cloud.githubusercontent.com/assets/10957765/6478943/064285cc-c267-11e4-9a06-a57f7ea41242.png)

**Comment by baev** [comment]
@LooMaclin why are you think that it is incorrect title? 

Each testNG test has **suite**, **test** and **test-method**. Allure only has two levels: **suite** and **case**. So, we match it like this: 

* Allure suite -> "testNg.suite : testNg.test[testNg.test.params]" 
* Allure case -> "testNg.test-method"

**Comment by LooMaclin** [comment]
@baev Hmm. Strange. Perhaps I hadn't realized before, because the tests in testng.xml no settings. Now understand that this is not an error. Then another question. Please bring an example of how I can add the 3rd level in reports like the tests were described in testng.xml ?

**Comment by baev** [comment]
> Please bring an example of how I can add the 3rd level in reports like the tests were described in testng.xml ?

There are no way to make such thing (

**Comment by baev** [comment]
Now we are working on new plugin system which can help you to add new tabs, so I guess tab for testNg with 3rd level soon have

**Comment by LooMaclin** [comment]
@baev Thanks for the answers. Wait, when it will be possible to add new levels to test announced in testng.xml. In my opinion this will make the generated reports more informative and more relevant pattern xUnit. Good luck in development!
