### ISSUE TITLE
Double scroll with HTML attachments

### ISSUE THREAD

**Issue by buhter** [allure-framework/allure-core#522]
If we have large(high) HTML attachment double vertical scroll may appear.
It depends on window height and looks a little bit unpretty.
On 100% reproduces in FF(Win/Mac).
Allure version - 1.4.8
Screenshot attached.
![2015-03-12_1245](https://cloud.githubusercontent.com/assets/592726/6615689/435e3f18-c8b7-11e4-9ff3-b3879e786d55.png)

**Comment by baev** [comment]
@buhter sorry for the delay.

Summon @just-boris

**Comment by just-boris** [comment]
it will be okay when #721 will be merged

**Comment by baev** [comment]
all should be fine
