### ISSUE TITLE
Display duration of steps, not just start time

### ISSUE THREAD

**Issue by pupssman** [allure-framework/allure-core#532]
We've got a pressing issue of analysing complex (and complicated) tests with lots of steps.
The thing is we need to find out which steps take most of the time to move them to common setup, for example. But now the only information on step execution present is the start time, which is not enough.

It would be great (in increasing order of awesomness) to:
* have end time OR duration of step visible in the report,
* see timeline of particular test case that shows how the steps contribute duration,
* have automated stats collected on steps duration, like we have for common errors now.

Essentially, this looks like a profiling-tool-like-facade for the report data.

But the duration is a really good starting point)

**Comment by buzdin** [comment]
+1 for duration AND start time.

**Comment by pupssman** [comment]
@just-boris told me once that start time was chosen over duration because it can be nicely formatted for fixed width to have a nicer view. But I can't see what's good is to have that start time -- only if you test has lots of stuff happening outside of steps, maybe?

**Comment by pupssman** [comment]
Like here: http://ci.qatools.ru/job/allure-core_pull-request/55/artifact/allure-report-preview/target/allure-report/index.html#/home/273a52470aa82c5f/526e2a0a7dce4546

**Comment by buzdin** [comment]
Well, the point is traceability to other resources. For example system log files. You would want to know where to look for a specific log file messages, so test step start time is relevant in this case, otherwise you would have to use calculator.

**Comment by pupssman** [comment]
See https://github.com/allure-framework/allure-core/pull/533#issuecomment-82366846
Is that way better?

**Comment by buzdin** [comment]
What if you move something to the right side, like duration?

**Comment by pupssman** [comment]
@buzdin that's exactly what we've done in #533 -- hope it to be released soon

**Comment by baev** [comment]
fixed via #553.
