### ISSUE TITLE
Change structure of allure-report-face

### ISSUE THREAD

**Issue by baev** [allure-framework/allure-core#546]
We are working on new plugin system, so now the time for some changes in structure of report face:

1. All tabs is plugins now
1. `index.html` should contains list of plugins.

Assumed structure of the report face:

```
flash/
plugins/
- overview/
-- manifest.json  - information about plugin id, plugin icon etc
-- script.js
-- style.css
-- template.tpl.html
- defects/
- xunit/
- timeline/
- behaviour/
- graph/
img/
translations/ 
vendor/
WEB-INF/
index.html
```

**Comment by baev** [comment]
@just-boris correct me if I wrong

**Comment by just-boris** [comment]
Generally ok. Also, we should not forget about core scripts

**Comment by just-boris** [comment]
And what about unit tests? How are we going to place them?

**Comment by baev** [comment]
@just-boris as you wish

**Comment by baev** [comment]
done via #554
