### ISSUE TITLE
no overview icon in the generated report

### ISSUE THREAD

**Issue by cgoswami** [allure-framework/allure-core#559]
hi,

just started using allure cli to generate reports for nose tests, i do not see any overview icon. i was testing the environment variables, but cant see them since no overview see attached image. I am missing something ? is there an pre-requisite  for having overview ?

![image](https://cloud.githubusercontent.com/assets/2392271/7271341/f852e22a-e8e2-11e4-8d78-71b4b1478576.png)

**Comment by baev** [comment]
Could you please specify your report version?

**Comment by cgoswami** [comment]
for the web report : Version: 1.3.9

got this from the cmd line for cli
λ allure version
2.3

**Comment by baev** [comment]
Overview tab since 1.4. You can specify report version using **-v 1.4.11**

**Comment by cgoswami** [comment]
thanks that did work but generated an error

```
λ allure report generate noseresults\ -v 1.4.11
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [java.net.URLClassLoader@6ba67ab5] whereas object of type
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@62e8ef4c].
log4j:ERROR Could not instantiate appender named "console".
```
should i be worried about this ?

**Comment by cgoswami** [comment]
I just saw there is already an issue for this, thanks for your help again :)
