### ISSUE TITLE
Allure Gradle+JUnit example

### ISSUE THREAD

**Issue by FylmTM** [allure-framework/allure-core#562]
Hi,

Recently I spent some time to add Allure to our Gradle+JUnit project.
I extracted example (based on TestNG example) - [neueda/allure-gradle-junit-example](https://github.com/neueda/allure-gradle-junit-example).

Take look at [AllureTestRunner](https://github.com/neueda/allure-gradle-junit-example/blob/master/src/test/java/ru/yandex/qatools/allure/junit/AllureTestRunner.java) class.

What do you think? There are any better alternatives?

**Comment by vania-pooh** [comment]
@FylmTM please take a look at the following example for TestNG https://github.com/allure-examples/allure-gradle-testng-example/blob/master/build.gradle What I don't like in your build.gradle is that you're using CLI commands to generate report. You don't need it as Gradle can execute Java directly. However JUnit example will differ a bit from TestNG because TestNG automatically loads AllureListener class from classpath whereas for JUnit you need to specify this class manually in build.gradle.

**Comment by vania-pooh** [comment]
@baev: any other thoughts?

**Comment by FylmTM** [comment]
@vania-pooh I was unsuccessful to find how automatically pass AllureListener to JUnit. 

Maybe you can point me to Java classes that I should use for report generation?

**Comment by vania-pooh** [comment]
@FylmTM probably this is not implemented in Gradle DSL. Main generator class is https://github.com/allure-framework/allure-core/blob/c8d505d6b9e3a60c8c8afe06b82c0095e807334c/allure-report-data/src/main/java/ru/yandex/qatools/allure/data/AllureReportGenerator.java

**Comment by FylmTM** [comment]
@vania-pooh check out updated example version.
I removed allure-cli calls from build.gradle. So, example now looks more like testng example.

Also I moved information about allure-cli to README.

------
About report generation using Java - looks like that this should be developed in some sort of Gradle plugin. 
My point of view - that this should be done separately.

**Comment by vania-pooh** [comment]
@FylmTM I think your current code will not work as AllureListener is not loaded. Isn't it?

**Comment by FylmTM** [comment]
@vania-pooh `AllureListener` is added in [AllureTestRunner](https://github.com/neueda/allure-gradle-junit-example/blob/master/src/test/java/ru/yandex/qatools/allure/junit/AllureTestRunner.java#L22)

**Comment by vania-pooh** [comment]
@FylmTM if it works for you then that's ok. You could tranfer this example to allure-examples if you wish.

**Comment by FylmTM** [comment]
@vania-pooh Yes. How this (transfer) can be done?

**Comment by vania-pooh** [comment]
Please go to repo settings and use transfer functionality there.

**Comment by FylmTM** [comment]
@vania-pooh Error: You don't have admin rights to allure-examples

**Comment by vania-pooh** [comment]
Ok, then please push to https://github.com/allure-examples/allure-gradle-junit-example. You should be able to do that.

**Comment by FylmTM** [comment]
Done. I think this issue can be closed.

**Comment by baev** [comment]
@FylmTM I think better to implement gradle test listener. Your code will not work with JUnit parameterized, theories, spring etc

**Comment by FylmTM** [comment]
@baev Thanks for the tip. I am going to check out this feature deeper soon.

**Comment by baev** [comment]
Some thoughts:
* Gradle reporing api https://gradle.org/docs/current/javadoc/org/gradle/api/tasks/testing/TestListener.html
* Also you can write your own allure-gradle-plugin. In this case you should add run listener and aspectj agent (you can see jacoco-gradle-plugin as example how to do it). 
* PR to Gradle with JUnit run listeners support https://github.com/gradle/gradle/pull/416

**Comment by vania-pooh** [comment]
Closing this one. Created respective issue in example repository.
