### ISSUE TITLE
Report generation sometimes hangs when using version 1.4.11

### ISSUE THREAD

**Issue by hmax** [allure-framework/allure-core#568]
Using jenkins plugin we started seeing bad behaviour - from time to time allure report generation step hangs indefinitely, and cancelling it makes slave used for generation broken. All consequent jobs that are trying to launch on it fail with exception talking about channel being already closed

**Comment by pupssman** [comment]
Important fact: `1.4.5` is not affected by this problem,  `1.4.11` is sorta affected.

@eroshenkoam said that there are some major changes in networking between these version -- and so says the diff. By any change, are you ignoring random `IOException`s or somehting?

**Comment by baev** [comment]
@pupssman since `1.4.6` we are using `Groovy` instead `XSLT` to generate the report

**Comment by pupssman** [comment]
@baev we'd like to have some pointers as where to investigate. Due to hanging we are currently limited to 1.4.5

**Comment by baev** [comment]
@pupssman I propose you to use `1.4.14` =)

**Comment by pupssman** [comment]
@baev because it had some IO-related bugs fixed?

**Comment by baev** [comment]
yep. And `1.4.14` at least 10 times faster then `1.4.5`

**Comment by pupssman** [comment]
@baev great! We'd still like to see those IO-related issues/PR's to see if they can possibly fix our veird hanging behaviour.

**Comment by baev** [comment]
https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.14
https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.7

**Comment by baev** [comment]
Any updates on this?

**Comment by baev** [comment]
should be fixed with new `allure-commandline`
