### ISSUE TITLE
Annotation lits 

### ISSUE THREAD

**Issue by martinotu** [allure-framework/allure-core#572]
Hi,
I found this project amazing, well done!

I have one question/improvement, is it possible to specify (from the code or config) a list of annotation to consider as steps?

I mean, can be possible to automatically log any call to a specific annotation, like, @FindBy?
This will be very handy while working 3rd party libraries annotations.

Cheers,
Mt

**Comment by baev** [comment]
@martinotu you can't... but

It is easy to implement 3rd party lib thats will handle other annotations! All you need - is implement your aspects([AspectJ](https://eclipse.org/aspectj/)):  take a look to the [our step aspects](https://github.com/allure-framework/allure-core/blob/master/allure-java-aspects/src/main/java/ru/yandex/qatools/allure/aspects/AllureStepsAspects.java) and our [adaptor api](https://github.com/allure-framework/allure-core/blob/master/allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/Allure.java).

E.g. if you need to add step you simply can use the following code:

```java
Allure.LIFECYCLE.fire(new StepStartedEvent("my step"));

// some code here

Allure.LIFECYCLE.fire(new StepFinishedEvent());
```

AspectJ provide to you lots of different pointcuts - such as *the method with annotation X called* or *the value of the field in class Y changed*.

**Comment by martinotu** [comment]
@baev Thanks!

Can you give me some more details?

Once I have created my AllureStepsAspects how can I make sure its called?

I use maven-surefire-plugin with argline to trigger allure.

Thanks again,
Mt

**Comment by baev** [comment]
You should create `aop-ajc.xml` file in `META-INF` folder in resources. Or simply add the following plugin to your `pom.xml`:

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>aspectj-maven-plugin</artifactId>
    <version>1.4</version>
    <configuration>
        <showWeaveInfo>true</showWeaveInfo>
        <source>${compiler.version}</source>
        <target>${compiler.version}</target>
        <Xlint>ignore</Xlint>
        <complianceLevel>${compiler.version}</complianceLevel>
        <encoding>UTF-8</encoding>
        <verbose>false</verbose>
        <outxml>true</outxml>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>compile</goal>
                <goal>test-compile</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjtools</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
    </dependencies>
</plugin>
```

Then you should add your lib to classpath. 

See http://andrewclement.blogspot.ru/2009/02/load-time-weaving-basics.html

**Comment by baev** [comment]
@martinotu I close it for now. Feels free to reopen
