### ISSUE TITLE
I want to see when the reporter can't find the test result xml

### ISSUE THREAD

**Issue by pdoggyster** [allure-framework/allure-core#595]
I want to see in the test report when the reporter can't find the test result xml.
Now everything is pass.

**Comment by vania-pooh** [comment]
@pdoggyster i.e. you mean that Maven plugin should return errors when no XML files are present.

**Comment by pdoggyster** [comment]
@vania-pooh 
when it try to generate a report but the source dir is empty than the report is created but it is shown everything okay but the report is empty.
example: I use the TC report generator or command line tool.

**Comment by baev** [comment]
I propose the following solution:

1. Add `failIfNoResults` parameter to `AllureReportGenerator` and throw a `ReportGenerationException` with cause if no results and `failIfNoResults` is true.
2. Add `failIfNoResults` parameter to `AllureReportBuilder`, and all our report build tools.

@eroshenkoam what are you think?

**Comment by baev** [comment]
Or better always fail the report generation if no results. No one want to see the empty report

**Comment by pdoggyster** [comment]
Is this change already available?

**Comment by baev** [comment]
@pdoggyster since 1.4.15. I going to release it next week

**Comment by baev** [comment]
Note: exception will be thrown only when you generate report 1.4.15 or higher. Other reports will be empty

**Comment by pdoggyster** [comment]
Great, thanks!
