### ISSUE TITLE
Environment tab is not displaying properties from environment.xml

### ISSUE THREAD

**Issue by pupssman** [allure-framework/allure-core#601]
Apparently, somewhere between `1.4.11` and `1.4.14` a bug was introduced that causes properties from `environment.xml` not to be displayed in the report.

**Comment by pupssman** [comment]
@eroshenkoam @baev can you see if this is true? Have we got any tests on that?

**Comment by baev** [comment]
Since 1.4.12 overview shows only first 10 properties. To see other you should use `environment` tab (on dev for now https://github.com/allure-framework/allure-core/pull/590)

**Comment by pupssman** [comment]
We've discussed this with @baev and decided to implement an expandable view for the environment tab on the Overview pane.

**Comment by baev** [comment]
fixed via #605
