### ISSUE TITLE
Need a button to copy stack trace

### ISSUE THREAD

**Issue by sergeychipiga** [allure-framework/allure-core#607]
I'm definitely sure, that we need a button to copy stackstrace to have ability to move it to testreport quickly

**Comment by baev** [comment]
@sergeychipiga english please

**Comment by baev** [comment]
I personally don't like it. IMHO test case page already overloaded. I propose to think about new API (new kind of plugins??) to add links/buttons to test case page.

@allure-framework/qatools-team any comments and ideas?

**Comment by vania-pooh** [comment]
@baev I would create a set of predefined regions (div tags with no content by default) in HTML where buttons can be inserted via client-side plugin API.

**Comment by just-boris** [comment]
@vania-pooh anyway it's nice to have reusable component with copy-paste feature, but the main trouble everywhere, it how to place this button and not to make other areas less usable

**Comment by admizh** [comment]
@just-boris Maybe try use hot keys?

**Comment by dstoianov** [comment]
+1, 
waiting for a button...
it will comfortable to copy and then past it in "Analyze Stacktrace" in IDEA

**Comment by just-boris** [comment]
Well, here is a good news: https://github.com/zenorocha/clipboard.js – it is flash-free copy component. It can be placed in everywhere, whatever you can.

But now I have to work on webdriverio-allure-adapter, so I don't know, when I can do it

**Comment by baev** [comment]
Should be done via custom Allure plugin
