### ISSUE TITLE
Support for nested suites

### ISSUE THREAD

**Issue by OLibutzki** [allure-framework/allure-core#613]
Hi,

do you plan to support nested suites?

Kind regards
Oliver

**Comment by baev** [comment]
It would be nice to add support for nested suites. Since 2.0 we are going to remove suites from model and use labels instead. But I don't know how to specify the suites order in this case. 

What the problem you trying to solve? Could you please give us more information about your case?

**Comment by OLibutzki** [comment]
I use  have several nested suites in my Java testframework. Currently I just can have three levels: Suite, Test case and step. I would like to have an infinite depth.

**Comment by baev** [comment]
@OLibutzki thanks, I got it. For now you can use features for 2-level grouping.

**Comment by Pr-Mex** [comment]
Всем привет. Вставлю свои 5 копеек.
У меня на проекте будет более 700 фич, которые хранятся  иерархически, по подсистемам конфигурации 1С.
Глубина вложенности может быть произвольной.
Поэтому в отчете нужен improvement, чтобы можно было отобразить иерархию фич с любой степенью вложенности.

**Comment by nzhenry** [comment]
This could possibly apply to nested describe blocks in javascript frameworks mocha and jasmine?

**Comment by baev** [comment]
Done in Allure 2
