### ISSUE TITLE
Arquillian Attachment

### ISSUE THREAD

**Issue by kennedyoliveira** [allure-framework/allure-core#618]
I’m with a problem, i searched and not found any solution.

I’m using Arquillian, Drone and Graphene with phantomJS to do integration tests, the problem is, i wanna attach a screenshot of the browser when i get any error, but Arquillian doesn’t let me return a byte[] from methods, it needs the methods to be void and receive no parameter.

Needs an alternative way to attach files to report.

**Comment by baev** [comment]
You can use our java API:

```java
Allure.LIFECYCLE.fire(new MakeAttachmentEvent(...));
```

**Comment by kennedyoliveira** [comment]
@baev  it worked! Thx!
