### ISSUE TITLE
Jenkins plugin > Overview > Xunit widget doesn't show all suites

### ISSUE THREAD

**Issue by gkiszczak** [allure-framework/allure-core#621]
Hi,

Is there a way to show all suites in overview Xunit widget? 
Currently only 10 suites are displayed and I have 16. 
I'm looking on overview as on summary and I would like to see general results for all suites. 

BTW. Was jenkins plugin removed?

**Comment by baev** [comment]
@gkiszczak jenkins plugin moved to jenkinsci organization https://github.com/jenkinsci/allure-plugin

**Comment by gkiszczak** [comment]
@baev Thank you for such quick answer. What about first part of the issue? 
Is it by design that xunit on overview page displays only part of the suites?

**Comment by baev** [comment]
> Is it by design that xunit on overview page displays only part of the suites?

Yep, all overview widgets (except environment) shows only 10 items. We are going to create link "see more" to the tab. I afraid that if we will show all the suites, overview page will be unusable.

**Comment by gkiszczak** [comment]
Ok. Thank you. Looking forward to see new releases.
