### ISSUE TITLE
Video @Attachment compatibility

### ISSUE THREAD

**Issue by 7170** [allure-framework/allure-core#624]
Hi guys,

It will be amazing that video Attachments are compatible with more browsers

Maybe with video tags or plugin use ?

**Comment by baev** [comment]
@7170 thanks for suggesting!

Lets use video html5 tag (browser support of this feature: http://caniuse.com/#search=video). Could you please send us the pull request? (the PR shows how to add attachment type support https://github.com/allure-framework/allure-core/pull/526/files)

**Comment by sskorol** [comment]
@7170 would be available in new version, after merging new face. Already created PR.

**Comment by sskorol** [comment]
Already merged with master. Issue could be closed I believe.

**Comment by baev** [comment]
closed via #777
