### ISSUE TITLE
Highlight non-empty comments for test cases

### ISSUE THREAD

**Issue by msventukh** [allure-framework/allure-core#628]
Some time ago you have added possibility to write comments for test-cases. It's a very good feature, but there is a little problem — QA engineer can't distinguish empty and non-empty comment, he should click on comment pseudolink to see comment content.
It will be great to highlight comment pseudolink for non-empty comments, so QA engineer can see if there is some important information attached as a comment for test case.

**Comment by baev** [comment]
@msventukh thanks for feedback!

As far as I know the comments to test cases it is our internal feature. So could you please write the same message to allure@yandex-team.ru and lets discuss.
