### ISSUE TITLE
Cannot close testsuite on XUnit once opened

### ISSUE THREAD

**Issue by jamesbuckley** [allure-framework/allure-core#630]
In Allure version 1.4.13 you cannot close the suite view once it has opened on xUnit.

In previous versions, the url for xUnit was /#/home.
In 1.4.13, it is /#/xunit.

When you attempt to close the suite view, you get the following error from AngularJS:

Error: Could not resolve 'home' from state 'xunit'
    at Object.transitionTo (angular-ui-router.js:3074)
    at Object.go (angular-ui-router.js:3007)

**Comment by shimkiv** [comment]
#594

**Comment by baev** [comment]
@jamesbuckley fixed in 1.4.15

@shimkiv :+1:
