### ISSUE TITLE
Dashboard: steps are sticky when scrolling long list

### ISSUE THREAD

**Issue by n4me1ess** [allure-framework/allure-core#636]
Steps are sticky when scrolling long list. 
Safari v 8.0.7 (10600.7.12)
OS v10.10.4
![2015-07-29 19 08 59](https://cloud.githubusercontent.com/assets/12499583/8960170/2784ac44-3628-11e5-9977-62d1c51ab4d9.png)

**Comment by just-boris** [comment]
Looks related https://github.com/allure-framework/allure-core/issues/410

**Comment by baev** [comment]
Closed as no response
