### ISSUE TITLE
How to distinguish between testsuite and testcase on the report

### ISSUE THREAD

**Issue by jonsteuwart** [allure-framework/allure-core#652]
Using Selenium C# web driver with NUnit for automation. I am generating Allure report using command line and my report gets fantastically created but I need help on the following issue:
I have the following structure using Page object model (2 Test and 1 Page). Now when I see the report it shows at the top Test run (2 testsuites, 2 testcases) and each testcase is a testsuite. I want it to say 1 testsuites, 2 testcases. How do I do that?

```
namespace ApplicationName.TestCases
{
    [TestFixture]
    class VerifyCreateOrder
    {

        IWebDriver driver;
        [SetUp]
        public void Initialize()
        {
            driver = new FirefoxDriver();
        }

        [TestCase]
        public void doCreateOrder()
        {
            LoginPage loginPage = new LoginPage();
            //some Assertion

         }
    }
}
```
```
namespace ApplicationName.TestCases
{
    [TestFixture]
    class SearchOrder
    {

        IWebDriver driver;
        [SetUp]
        public void Initialize()
        {
            driver = new FirefoxDriver();
        }

        [TestCase]
        public void doSearchOrder()
        {
            LoginPage loginPage = new LoginPage();
            //some Assertion

         }
    }
}
```
```
namespace ApplicationName.Pages
{
    class LoginPage
    {

        public void doLogin(IWebDriver driver, String username, String password)
        {
            driver.Navigate().GoToUrl("http://www.mysite.com");
            driver.FindElement(By.Id("xyz")).SendKeys(username);
            driver.FindElement(By.Id("xyz")).SendKeys(password); 
            driver.FindElement(By.Id("xyz")).Click(); 

        }
    }
}
```

I read about the NUnit suite attribute at http://www.nunit.org/index.php?p=suite&r=2.5.5 and created a c# class with enumerator as described but how do i call it/wire it? What changes do I need to make for my test classes?

```
namespace NUnit.Tests
{
    public class MyTestSuite
    {
        [Suite]
        public static IEnumerable Suite
        {
            get
            {
                ArrayList suite = new ArrayList();
                suite.Add(new VerifyCreateOrder());
                suite.Add(new SearchOrder());
                return suite;
            }
        }

    }
}

```

**Comment by baev** [comment]
@jonsteuwart sorry for the delay, the nunit adaptor supported mostly by the community, there is nothing I can help you with. So you can create an issue in [nunit adaptor repository](https://github.com/allure-framework/allure-nunit2).

**Comment by jonsteuwart** [comment]
@baev No Problem. I appreciate the hard work you guys are already put/putting. I have posted it in the nunit section. Hope I get someone to reply there. Thanks for your reply!

**Comment by baev** [comment]
thanks! 

ref https://github.com/allure-framework/allure-nunit2/issues/15
