### ISSUE TITLE
allure reporting for Jenkins should have back to Jenkins button

### ISSUE THREAD

**Issue by bgvianyc** [allure-framework/allure-core#654]
When using the reports, it the navigation can become so nested that one would have to press the back button many time or edit the url to get back to Jenkins. It would be helpful if there was a button to bring you back to Jenkins.

**Comment by baev** [comment]
@bgvianyc thanks for suggestion. The allure report has such ability, so we are going to implement this feature in next plugin release

**Comment by baev** [comment]
I guess the next plugin release is coming this week so stay turned

**Comment by baev** [comment]
and could you please use this repo https://github.com/jenkinsci/allure-plugin for creating issues for jenkins plugin next time)

**Comment by bgvianyc** [comment]
ok, great. thanks

**Comment by baev** [comment]
fixed in latest jenkins allure plugin
