### ISSUE TITLE
Allure Report time is incorrect/wrong

### ISSUE THREAD

**Issue by jonsteuwart** [allure-framework/allure-core#667]
I am using C# with NUnit. The Allure report time is 5 hrs ahead of my local time. Does anyone have this issue or know the cause?

**Comment by baev** [comment]
@jonsteuwart sorry for the delay

> The Allure report time is 5 hrs ahead of my local time

Could you please specify the page you are talking about

**Comment by pdoggyster** [comment]
I'v also but it is 2 hrs ahead of my local time. I'm in the UTC+1 timezone.
I ran my test example at 10:00 but when I generated the allure report and check it then it shows that start time 12:00

**Comment by baev** [comment]
@pdoggyster is it time from `total` widget you are talking about?

**Comment by pdoggyster** [comment]
The start time in the -testsuite.xml
 <test-case start="1443172688519" stop="1443172706998" status="passed">

1443172706998 -> 
currentmillis.com ->
to UTC time and date: Fri Sep 25 2015 09:18:26
to local time and date: Fri Sep 25 2015 11:18:26

A local time appears in the riport but the UTC would be good.

**Comment by just-boris** [comment]
You see times in report with the same timezone that you see time at system clock. If you don't, this can be a bug.

@pdoggyster @jonsteuwart Does the time in report match with time at your system clock?

**Comment by pdoggyster** [comment]
No, the report the not match at my system clock. The report time is 2 hrs ahead of my system time.

**Comment by just-boris** [comment]
That's weird.

@pdoggyster Could you please execute in browser console: 
```
new Date()
```
And show me the result and system time at that moment?

**Comment by pdoggyster** [comment]
See the pictures:
![2015-09-28 11_18_59](https://cloud.githubusercontent.com/assets/12031285/10131786/124cf4aa-65d3-11e5-9e3b-34fe7dfcfc21.jpg)

**Comment by just-boris** [comment]
Well, there is nothing mysterious, xml in the report just has timestamp from the future :)

Are you generating report of some remote server? What time and zone is set there?

**Comment by pdoggyster** [comment]
No, I generated this machine.

**Comment by just-boris** [comment]
What does it mean? Are you using virtual box or something?

**Comment by pdoggyster** [comment]
Yes, this is a virtual machine (azure machine)

**Comment by just-boris** [comment]
Well, so I guessed that the machine has wrong time settings. Can you check current time there?

**Comment by pdoggyster** [comment]
11:35?:)

**Comment by pdoggyster** [comment]
The time the machine is good.

**Comment by just-boris** [comment]
Well, but what is UNIX-time (in milliseconds) is there?
Found that `allure-nunit` uses [this code](https://github.com/allure-framework/allure-csharp-commons/blob/master/AllureCSharpCommons%2FUtils%2FAllureResultsUtils.cs#L52) to get current time
```c#
DateTime.Now.ToUnixEpochTime();
```

**Comment by pdoggyster** [comment]
![2015-09-28 12_00_14-](https://cloud.githubusercontent.com/assets/12031285/10132774/92233f68-65d8-11e5-96c3-30fbe285124d.jpg)

**Comment by just-boris** [comment]
Well, are you sure that `.NET` framework use the same mechanism for getting current time.

**Comment by pdoggyster** [comment]
I think this problem solved: https://github.com/allure-framework/allure-csharp-commons/commit/db1ee73c5846ef13dddb69da56759e9715dbc99e

So If this fix will be released then I think that this problem will resolve.

**Comment by baev** [comment]
I guess we can close it
