### ISSUE TITLE
Using spring-agent java annotations are not processed

### ISSUE THREAD

**Issue by GiannisPapadakis** [allure-framework/allure-core#668]
The problem here is that custom annotations (Step-Attachment) are not processed even if i use the aspectjweaver as javaagent. In my surefire settings i use another javaagent also for load time weaving:
 <forkCount>1</forkCount>
   <argLine>
          -javaagent:${settings.localRepository}/org/springframework/spring-agent/2.5.6/spring-agent-2.5.6.jar -noverify
</argLine>

After using also aspectjweaver for annotation processing i can not see in the report neither attachments nor logging steps.

Thanks

**Comment by vania-pooh** [comment]
Summon @baev

**Comment by lanwen** [comment]
@baev is any way to combine agents?

**Comment by vania-pooh** [comment]
How about this one: http://stackoverflow.com/questions/872657/how-do-i-start-my-java-program-with-more-than-one-java-agent

**Comment by GiannisPapadakis** [comment]
I did the proposed solution from stackoverflow but with no success.

**Comment by baev** [comment]
http://www.jayway.com/2009/12/15/load-time-weaving-spring-and-maven/

**Comment by baev** [comment]
BTW the issue is not on Allure side
