### ISSUE TITLE
[Enhancement] Integrated Cucumber with TestNG support

### ISSUE THREAD

**Issue by GiannisPapadakis** [allure-framework/allure-core#670]
Hi it would be nice to have cucumber reports separated from TestNG ones if TestNG runner used for Cucumber. 
Dependency used
groupId:info.cukes
artifactId:cucumber-testng
version:1.2.4

**Comment by baev** [comment]
@GiannisPapadakis thanks for suggestion

I have no idea what are you talking about.

**Comment by GiannisPapadakis** [comment]
@baev 

I am using the dependency described above for running cucumber features with TestNG runner. In @Test methods we can provide one or multiple .feature files. We have a listener that extends  ru.yandex.qatools.allure.testng.AllureTestListener and i can override onTestStart in order to start new TestSuiteStartedEvent (Here the test method behaves as a suite). The problem is that in AllureTestListener executed onStart and reports TestSuiteStartedEvent in the beginning with the name of the test method that runs the cucumber feature. So ideally i would like to configure the listener if running cucumber. Allure supports Cucumber-JUnit and TestNG separately but i would like to configure listener if cucumber runs with TestNG.

**Comment by baev** [comment]
I guess you should write your own adaptor for cucumber-testNg

Note: in case you extend `ru.yandex.qatools.allure.testng.AllureTestListener` you should use the  `spi-off` classifier for avoid the results duplication.

**Comment by GiannisPapadakis** [comment]
Ok thanks @baev i will try to implement a new adaptor and let you know

**Comment by baev** [comment]
closed due to no response
