### ISSUE TITLE
Provide a way to work with Allure CLI tool offline

### ISSUE THREAD

**Issue by bartoszkaczorek** [allure-framework/allure-core#673]
Provide a way to work with Allure CLI tool offline - currently from what I understand it's downloading maven artifacts as part of it's process and that causes issues when working behind proxy with authentication or without internet connection. Actually I think CLI tool should not use maven at all - I would use allure-maven-plugin if I wanted to go maven path. I'm trying to use it for javascript project so dealing with maven seems not correct here.

**Comment by baev** [comment]
@bartoszkaczorek thanks for feedback!

New command line tool works in offline mode. See http://wiki.qatools.ru/display/AL/Allure+CLI for more information

**Comment by bartoszkaczorek** [comment]
Great to hear that! Can you tell if Allure Jenkins plugin will be able to work offline as well? Had similar issues with it and that was my initial reason to use allure-cli instead.

**Comment by baev** [comment]
> Can you tell if Allure Jenkins plugin will be able to work offline as well?

It is almost done, see https://github.com/jenkinsci/allure-plugin/pull/23
