### ISSUE TITLE
Allure cross browser reports

### ISSUE THREAD

**Issue by dhoulker** [allure-framework/allure-core#684]
Hello,

I'm not sure if this is the right place to ask this question - please redirect me if not!

We are using the allure reports with our tests, and its working really well. 

We run the same tests against multiple browsers. 

I was wondering if anyone could share an approach for this - should we be creating one report per browser? Is there anyone to have one report that shows each test run against multiple browsers?

Thanks,

Dave

**Comment by vania-pooh** [comment]
Hi,
IMO your choice should depend on multiple things. That's a good idea to have a relatively small report so it's possible to investigate it fast. So if you have 10000 cases for each browser I would generate separate reports. If that's not the case simply use @Features or @Stories to group cases by browser.

**Comment by baev** [comment]
btw you can use our gitter chat (https://gitter.im/allure-framework/allure-core) or stackoverflow for such questions)

**Comment by dhoulker** [comment]
Thanks guys - i'll raise on future questions on SO or gitter in future
