### ISSUE TITLE
Allure cli not copying attachments to data dir

### ISSUE THREAD

**Issue by dnaren** [allure-framework/allure-core#686]
Am using allure cli in windows 7 to generate the allure report. The report is generated successfully - however, the attachments are not copied over to data\ directory - hence its not available to view from the report. 

Attaching the testsuite.xml, the corresponding testcase.json & also the screenshot of the allure report. 

Does it require any specific configurations for this to work? or some other issue? 

testsuite.xml:

![image](https://cloud.githubusercontent.com/assets/4179970/10379529/acbff706-6ddc-11e5-9fb8-eb13d00431c6.png)

testcase.json (generated by allure cli):

![image](https://cloud.githubusercontent.com/assets/4179970/10379563/e61d8522-6ddc-11e5-8194-e6ef033b0c19.png)

Allure Report:

![image](https://cloud.githubusercontent.com/assets/4179970/10379598/1ded3ee8-6ddd-11e5-9212-ff8dad8fe479.png)

**Comment by baev** [comment]
@dnaren thanks for suggestion. The problem is attachments should has `-attachment.*` suffix.

**Comment by dnaren** [comment]
@baev thanks for the quick response - changing the file naming did fix the issue. 

But quick question though, after the report is generated - the tests in XUnit plugin or the defects in Defect plugin - do not appear as links?

![image](https://cloud.githubusercontent.com/assets/4179970/10380068/b8e43468-6ddf-11e5-8a79-1f2c828788ae.png)

![image](https://cloud.githubusercontent.com/assets/4179970/10380074/c14d040e-6ddf-11e5-9bfa-78ba6f4eab24.png)

**Comment by just-boris** [comment]
There was some refactoring recently.
Upcoming version 1.4.20 will have links there. You can see preview of this version here: http://ci.qatools.ru/job/allure-core_master-deploy/Allure_report/index.html#/

**Comment by dnaren** [comment]
@just-boris cool will wait for it. Am closing this issue.

Allure reporting is awesome guys - good job. It gives better insight to our functional test automation.
