### ISSUE TITLE
Error: no main manifest attribute when CLI tool to generate report version 1.4.19

### ISSUE THREAD

**Issue by sharadJay** [allure-framework/allure-core#687]
I updated to version 1.4.19 for report generation from commandline tool and I see this error 
```
no main manifest attribute, in /Users/shjain/.allure/bundles/1.4.19/allure-bundle.jar
ERROR: Command aborted due to exception org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1).

```
Can somebody look at this issue ?

**Comment by vania-pooh** [comment]
@sharadJay this is a known issue - CLI was also updated to support new bundles format that does not contain Manifest. The solution is to update CLI.

**Comment by sharadJay** [comment]
@vania-pooh  yes I see this working now. Thanks for the update.

**Comment by NuclearPenguin** [comment]
I get the same error when trying to generate a report
```
no main manifest attribute, in C:\Users\user\.allure\bundles\1.5.0-RC1\allure-bundle.jar
ERROR: Command aborted due to exception org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1).
```

**Comment by CoHuK** [comment]
I also have same problem now.

**Comment by vania-pooh** [comment]
@CoHuK how about reading my comments above and updating CLI to the latest version?

**Comment by CoHuK** [comment]
Yes, already found solution..
