### ISSUE TITLE
Making a link to a specific tab

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-core#692]
Hi guys. Since Allure reports are written in AngularJs as a single page application, i was wondering if it's possible to make links to specific tabs? For example, if i want to send a link to developers with already open "Defects" tab, i thought that i could do something like ```http://teamcity:8080/jobid#defects``` but that doesn't seem to work. Should i use some other types of anchors or it's not supported ?

**Comment by just-boris** [comment]
We have permalinks to tabs. This is working fine on our Jenkins: http://ci.qatools.ru/job/allure-core_pull-request/Allure_report/index.html#/defects
@azakordonets try to add a slash before tab name: `http://teamcity:8080/jobid#/defects`. Also, the easiest way to get direct link to the tab is open that tab and copy link from address bar them.

**Comment by azakordonets** [comment]
For TeamCity it doesn't seem to work ```http://selenium:8111/viewLog.html?buildId=74018&buildTypeId=Dev_DevSeleniumPreconditions&tab=report__Root_Allure_Reports#/defects``` doesn't work

**Comment by just-boris** [comment]
Summon @baev 
do we have a teamcity for testing?

**Comment by baev** [comment]
@azakordonets TeamCity opens the report tabs in iframe and doesn't provide the anchor for it. So you can use link to the report link this http://selenium:8111/repository/download/Dev_DevSeleniumPreconditions/74018:id/index.html#/defects

**Comment by azakordonets** [comment]
Well, that doesn't work for me for some reason. Here's what kind of url i'm trying to use - ```http://selenium:8111/viewLog.html?buildId=74088&buildTypeId=Dev_DevSeleniumAnticoagulationOnly/index.html#/defects```

Also didn't work this way : 
```http://selenium:8111/viewLog.html?buildId=74088&buildTypeId=Dev_DevSeleniumAnticoagulationOnly&tab=report__Root_Allure_Reports/index.html#/defects```

**Comment by baev** [comment]
Allure has links to the tabs. So it's Teamcity related issue
