### ISSUE TITLE
Sort tests by status in XUnit widget

### ISSUE THREAD

**Issue by innokenty** [allure-framework/allure-core#695]
Since XUnit widget on main page does not show all the tests, it can happen so that it shows only successful tests by occasion when there actually are failed tests in the run.

![screen shot 2015-10-21 at 20 58 47](https://cloud.githubusercontent.com/assets/4004229/10645606/4b01e1fe-7837-11e5-84af-6c499db2c4a8.png)

**Comment by baev** [comment]
:+1:

**Comment by just-boris** [comment]
Can we make this on Java-side of the plugin?

**Comment by baev** [comment]
It should be done in Java side ofc
