### ISSUE TITLE
Display total running time in header

### ISSUE THREAD

**Issue by innokenty** [allure-framework/allure-core#699]
Currently time of report generation is displayed in navbar along with allure version and report size. It would be really convenient to be able to see tests start/finish time and the duration of the run there too. Probably instead of generation time.

**Comment by just-boris** [comment]
After our recent optimizations report generation time does not make sense as before.
I have no objections to replace it with test run execution time from xUnit tab.

**Comment by baev** [comment]
There is no more header in the report
