### ISSUE TITLE
How to add a new link on to the report 

### ISSUE THREAD

**Issue by msp248** [allure-framework/allure-core#701]
For exmaple , 

I want to add a link "google" on to the allure report which should direct me to the respective reference .

**Comment by baev** [comment]
@msp248 sorry for the delay. Could you please explain more clearly what exactly do you need? Is it link for whole report or for each suite/case/feature you have in mind? 

In case link for whole report there is few possibilities for you:

#### The report top-left link
Usually it is link to test execution system (CI). But if you want you can override it to whatever you need.

![2015-11-09 15 03 16](https://cloud.githubusercontent.com/assets/2149631/11033291/0f514ad0-86f3-11e5-924d-ae8556d3cc5d.png)

#### The environment variable
![2015-11-09 15 12 06](https://cloud.githubusercontent.com/assets/2149631/11033462/59cfcda6-86f4-11e5-9df3-9559156f063f.png)

**Comment by msp248** [comment]
No , actually I want a link on top of the report near allure logo which can
direct me to the link which I want , for. example to Google.com . currently
am replacing the index.HTML file using bat command post site execution .

let me know if you have any other ideas for this

**Comment by baev** [comment]
> I want a link on top of the report near allure logo

As I say you can add link on top-left near the allure logo. All you need if write environment.xml file to your results folder with the following structure:

```xml
<qa:environment xmlns:qa="urn:model.commons.qatools.yandex.ru">
    <name>Your google link name</name>
    <url>https://your-google-link.com</url>
</qa:environment>
```

**Comment by baev** [comment]
closed as answered, if you have other questions - you can create a new one
