### ISSUE TITLE
Error: no main manifest attribute when CLI tool to generate report version 1.5.0-RC1

### ISSUE THREAD

**Issue by Kovsh** [allure-framework/allure-core#707]
I've updated allure-cli to version 1.5.0-RC1 and got error

no main manifest attribute, in C:\Users\...\.allure\bundles\1.5.0-RC1\allure-bu
ndle.jar
←[0;31mERROR: ←[mCommand aborted due to exception org.apache.commons.exec.Execut
eException: Process exited with an error: 1 (Exit value: 1).

Could anybody help with this? 
Thanks

**Comment by vania-pooh** [comment]
Please update your CLI to the latest version. Somewhere during 1.4.0 development we switched from bundles with manifests to bundles without 'em.

**Comment by Kovsh** [comment]
@vania-pooh thank you for your prompt respond
At the same time, I've already updated to the latest version with command "allure upgrade". It updates to version 1.5.0-RC1 and it does not work. 
What version should I use or maybe some another trick?
Thank you.

**Comment by baev** [comment]
@Kovsh `allure-cli` was deprecated. You should use `allure-commandline` instead. See http://wiki.qatools.ru/display/AL/Allure+Commandline

**Comment by Kovsh** [comment]
@baev thank you, it works.
