### ISSUE TITLE
Removing attachments from passing tests

### ISSUE THREAD

**Issue by ehasenkamp** [allure-framework/allure-core#709]
Forgive me on this question, as it is described in your [documentation] (https://github.com/allure-framework/allure-core/wiki/Attachments), but I cannot seem to get this to work.  I've tried three things to delete my attachments for passed tests:

1. put ```allure.properties``` in my resource folder with an entry ```allure.report.remove.attachments=.*\.png```
2. set a command line parameter in my pom
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.16</version>
  <configuration>
    <encoding>UTF-8</encoding>
    <inputEncoding>UTF-8</inputEncoding>
    <outputEncoding>UTF-8</outputEncoding>

    <suiteXmlFiles>
      <suiteXmlFile>testng.xml</suiteXmlFile>
    </suiteXmlFiles>
    <testFailureIgnore>true</testFailureIgnore>
    <forkMode>always</forkMode>
    <argLine>
      -javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/1.8.5/aspectjweaver-${aspectj.version}.jar 
      -XX:PermSize=64M -XX:MaxPermSize=256M -Xms512M -Xmx512M 
      -Dallure.report.remove.attachments=.*\.png
    </argLine>
  </configuration>
  <dependencies>
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjweaver</artifactId>
      <version>1.8.5</version>
    </dependency>
  </dependencies>
</plugin>
```
3. set a system property entry in my code
```java
Properties props = System.getProperties();
props.put("allure.report.remove.attachments", ".*\\.png");
```

In all instances, attachments remain if the test case passes.  Am I missing something on this? Should this be set somewhere else?

In addition, if I have other file types, for example .xml file, I want to remove, can the entry be a delimited list, for example comma separated?

**Comment by baev** [comment]
@ehasenkamp sorry for the delay

could you please provide a sample project to reproduce the problem? 

> In addition, if I have other file types, for example .xml file, I want to remove, can the entry be a delimited list, for example comma separated?

The property is simply [java pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html). So you can use `|` as well

**Comment by ehasenkamp** [comment]
I appologize for the delay, I was not active last week.  Here is a [sample project](https://github.com/ehasenkamp/allure-sample-attachment).  The [README](https://github.com/ehasenkamp/allure-sample-attachment/blob/master/README) explains how the tests are executed.

**Comment by ehasenkamp** [comment]
I just realized, this is happening in 1.5.0-RC1, but not in 1.4.19.  In the sample above, it's using your RC version.  When I downgraded to 1.4.19, the png files were removed.

**Comment by baev** [comment]
@ehasenkamp I found the problem, thanks!

**Comment by baev** [comment]
We should call `fire(new RemoveAttachmentsEvent()...)` instead of 
https://github.com/allure-framework/allure-core/blob/master/allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/Allure.java#L189

And there is no test for some reason =(
