### ISSUE TITLE
I can't see entire error just this `RSpec::Core::MultipleExceptionError`

### ISSUE THREAD

**Issue by pushprajsingh05** [allure-framework/allure-core#711]
Issues:
Using it as command line tool has brought so many issues.
1. After setting this I can't use rspec spec/example_test_spec.rb command anymore. It forces me to use with prefix bundle exec
2. After executing command I get the .xml then I need to convert it, for that I have to be in "allure-ci" java project directory.
3. To run command one more time, I need to stop the server by pressing Ctrl+c
4. At last I have the report but it doesn't the entire log. At least tell me at which line error is.

**Comment by baev** [comment]
Summon @smecsia

**Comment by smecsia** [comment]
@pushprajsingh05 Do you use RSpec exceptions aggregation feature? If so, there is an issue in allure-rspec adaptor ([allure-rspec#58](https://github.com/allure-framework/allure-rspec/issues/58)) and this is probably the duplicate.

**Comment by baev** [comment]
@pushprajsingh05 btw thanks for suggestion.

> 2. After executing command I get the .xml then I need to convert it

Yep, you are definitely need to run `allure-commandline` to generate the report for xml results. The reason - xml is just a raw representation of your test results. Each test has its own result (In general you can run your tests in different environments). So then you need to create the report from such result. You can use `allure-commandline` or Jenkins Plugin or whatever you need to generate the report (an example you can integrate Allure to your own build server as we did).

> that I have to be in "allure-ci" java project directory.

Could you please explain what are you mean?

> To run command one more time, I need to stop the server by pressing Ctrl+c

In case you generate the report at localhost you need to start web server to serve the report cause Chrome security. Or you can run chrome with `--allow-file-access-from-files` flag. In case of Firefox it is not necessarily. Do you have any suggestions how to avoid of `Ctrl+c` to stop the server? When we should stop it? I can propose you `allure report open --no-web-server` command in case Firefox is your default browser.

**Comment by baev** [comment]
Closed as no response. Feel free to reopen.

**Comment by nachiketk21** [comment]
I am still facing this issue. Is there a solution to this ?
