### ISSUE TITLE
[Environment] A way to add test env. values via code.

### ISSUE THREAD

**Issue by L-Evg** [allure-framework/allure-core#713]
Issue
 Currently (v1.4.19) one can set test environment values via the environment.xml or environment.properties only. So, those files should be predefined or generated on the fly and placed in proper locations. That could be inconvenient in case of different test environments, specific CI approaches etc.

Suggestion
 Introduce an ability to set env. values via test code (e.g. inside some initialization piece). That way one can easily set/add info which is specific to a particular test run.
As for the implementation  - it could be done by implementing some env. values provider interface. Or by injecting the values via some AllureConfigurer.

**Comment by dimand58** [comment]
It would be great add env. variables via system properties (or this already implemented?)

**Comment by baev** [comment]
@L-Evg @dimand58 hi, sorry for the delay!

How to handle the situation when you run your tests at different runtime? For an example using different JVM for Java-tests? In this case you will get the few results folders, each folder contains different `environment.xml`. How to merge the environments? 

The main idea that your runtime (Jenkins, Teamcity, Maven, your own super cool build system) knows all about test run. Knows what you gonna test, which browser you are using etc. So runtime can provide the environment for the tests.  

So noone says that you can not simply write a dummy test (or script) that will provide an environment during tests execution.

**Comment by dimand58** [comment]
@baev thanks for answer. In my case this problem was resolved via button "Include build environment" in  Allure Jenkins Plugin

**Comment by baev** [comment]
I guess I can close this one. Feel free to reopen
