### ISSUE TITLE
Static files don't loading within CSP-restrictions

### ISSUE THREAD

**Issue by just-boris** [allure-framework/allure-core#715]
Content-Security-Policy is gonna be spreading across the web. So it is matters to make Allure work with it.

Allure doesn't work with the following headers:

```
Content-Security-Policy:sandbox; default-src 'none'; img-src 'self'; style-src 'self’;
```

**Comment by just-boris** [comment]
Ok, reproduced it on my local server. It seems that our report can't work in the so strict environment.

I will look for more suitable compromise.

**Comment by just-boris** [comment]
Now I have come up with the conclusion that we can't make Allure work in such restrictions. That CSP setting disallows executing any javascript on the page. Obviously, our report can't work with JS.

I made Allure work with a bit relaxed version of config:

```
'Content-Security-Policy', "sandbox allow-scripts allow-same-origin; default-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self'; style-src 'self';"
```

It allows us to use all static resources from the same domain and fetch data via AJAX as well.

//cc @georgecrawford

**Comment by georgecrawford** [comment]
@just-boris Do you know anything about how the CSP settings are configured in Jenkins? According to our systems engineer, we're using a very vanilla installation of Jenkins, with nothing special security-wise. Does Allure definitely work for you in a similar setup?

If you know how I can change the headers, please let me know.

**Comment by just-boris** [comment]
Found the following commit: https://github.com/jenkinsci/jenkins/commit/d3fb2c09f29007dce84a213ae8323df1105dcc30
Looks like latest Jenkins version has this feature. I will try to figure out

**Comment by georgecrawford** [comment]
Interesting - I'll also look into how we might configure this better.

**Comment by georgecrawford** [comment]
Ref: https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy

**Comment by georgecrawford** [comment]
OK, so using this command in the Script Console:
```
System.setProperty(hudson.model.DirectoryBrowserSupport.class.getName() + ".CSP", "script-src 'unsafe-inline' 'self';")
```
... I have it *almost* working. But there's something very strange that I don't understand - lots of UI elements seem corrupted, and there are thousands of JS console errors (`Error: [$interpolate:interr] `)

- both expand and collapse showing:
<img width="283" alt="screenshot 2015-12-11 20 37 51" src="https://cloud.githubusercontent.com/assets/84737/11754991/2f4de48e-a047-11e5-901b-eeafa05c8dc9.png">

- "Attachment not found", but it's there!
<img width="335" alt="screenshot 2015-12-11 20 37 59" src="https://cloud.githubusercontent.com/assets/84737/11754992/2f6343f6-a047-11e5-8d44-45252bf182b3.png">

- broken error:
<img width="595" alt="screenshot 2015-12-11 20 38 25" src="https://cloud.githubusercontent.com/assets/84737/11754993/2f6d5350-a047-11e5-8767-d246c6e0a065.png">

<img width="586" alt="screenshot 2015-12-11 20 38 41" src="https://cloud.githubusercontent.com/assets/84737/11754994/2f6df44a-a047-11e5-8281-73319f2f3e1c.png">

**Comment by just-boris** [comment]
Yes, that weird things are caused by some inline styles. I prepared a PR to fix it. https://github.com/allure-framework/allure-core/pull/716

For now, you can work around by adding `style-src 'self’ 'unsafe-inline'`

**Comment by georgecrawford** [comment]
I see the same problems with `script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';`.

**Comment by georgecrawford** [comment]
I downloaded the allure xml files, and it all looks perfect when I run `allure generate allure-results/ && allure report open` with CLI version 1.4.19. So it's definitely a Jenkins/CSP issue.

**Comment by just-boris** [comment]
:( Ok, then you can shut down the CSP at all, by setting it to `""` (empty string). I will come up with a better solution at the next week.

**Comment by georgecrawford** [comment]
Yep, it's fine when I do that. I'll keep on trying other combinations tool.

**Comment by georgecrawford** [comment]
Good news: I have it working now with just: `default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';`

**Comment by just-boris** [comment]
Updated our Jenkins docs. http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin
We consider that this setting would be the best solution for the issue.

**Comment by just-boris** [comment]
thanks @georgecrawford for the report and help

**Comment by SpyderWeiss** [comment]
For those of you having issues with this, I had to set BOTH Jenkins and Hudson properties for it to work, just run these in the /script window of your Jenkins server:
System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';")

System.setProperty("jenkins.model.DirectoryBrowserSupport.CSP", "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';")

**Comment by tonka3000** [comment]
thanks @SpyderWeiss , your solutions works :+1:

**Comment by akiikius** [comment]
Hi all, where can i find: /script window of the Jenkins server?

**Comment by nickwinn** [comment]
@akiikius https://<your jenkins host>/script OR Manage Jenkins >> Script Console

**Comment by adv-tsk** [comment]
When I run [Jenkins container](https://hub.docker.com/_/jenkins/), I get an error: **`Error: Could not find or load main class self`**
Run command:
`docker run --name jenkins -p 8080:8080 -p 50000:50000 --env JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP=default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';" --env JAVA_OPTS="-Djenkins.model.DirectoryBrowserSupport.CSP=default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';" jenkins`

**Comment by just-boris** [comment]
@adv-tsk You need to escape property. Currently, expression parsed as following

```
-Dhudson.model.DirectoryBrowserSupport.CSP=default-src
```
The rest of expression will be passed as a main class name.

Try this:

```
docker run --name jenkins -p 8080:8080 -p 50000:50000 \
    --env JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';\"" jenkins
```

Note extra `\"` around propery values.

**Comment by adv-tsk** [comment]
Thanks @just-boris, it works!)

**Comment by brpIHDUN** [comment]
I am still having issues with accessing reports in Chrome.
I did set the properties as per @SpyderWeiss 's comments. That fixed the issue for firefox only! I am a chrome lover and so is my whole team so we need it working on Google Chrome, any suggestions/solutions?

**Comment by Cycnicus** [comment]
+1 to brpIHDUN. This trick not worked in chrome.

**Comment by mobidevadmin** [comment]
+1 same issue in Chrome

**Comment by just-boris** [comment]
Hello, guys!

Could you tell more details about the current issue? Maybe we have got some regression here. A screenshot of console with errors would be so helpful there

**Comment by mobidevadmin** [comment]
![allure](https://cloud.githubusercontent.com/assets/10165479/20597576/2c2ef428-b24d-11e6-969d-71cb0cbb44f0.png)

**Comment by mobidevadmin** [comment]
Allright,

tried to add these lines in jenkins console via Firefox ( I did it in Chrome previously) - and it worked. So it's either Chrome or one need to add the lines twice in a row in order to make it applied:
```
System.setProperty("jenkins.model.DirectoryBrowserSupport.CSP", "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';")
System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';")
```

For the very first time i added that links i had an empty "Result", now it answered me with some extra lines.
Sorry for this kind of panic.
