### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by shex** [allure-framework/allure-core#717]
![image](https://cloud.githubusercontent.com/assets/50077/11789563/cb499f72-a29f-11e5-9342-17d05fb10bff.png)

**Comment by lanwen** [comment]
relates #715

**Comment by just-boris** [comment]
Yes, our CI-sever suddenly has been updated.
Now we gonna follow the instructions in our docs and will fix it tomorrow.

**Comment by just-boris** [comment]
should be fine now.
