### ISSUE TITLE
Unable to setup Allure on Jenkins

### ISSUE THREAD

**Issue by poohpeer** [allure-framework/allure-core#718]
I'm trying to configure Allure with Jenkins, but there are an errors that I can't get through.

1. encoding issue
2. Jenkins complete the run cycle with "Waiting for Jenkins to finish collecting data" and never update it.

[ Cant_set_encoding.txt](https://github.com/allure-framework/allure-core/files/62346/Cant_set_encoding.txt)

**Allure version:** 1.4.19
**Jenkins version:** 1.610
**Results file location:** /var/lib/jenkins/workspace/selenium/target/allure-results
Seems the results files get created successfully, but somehow Allure doesn't create the link for reports.

[eade93c4-4624-44d2-9560-8aaa6211bb54-testsuite.xml.zip](https://github.com/allure-framework/allure-core/files/62230/eade93c4-4624-44d2-9560-8aaa6211bb54-testsuite.xml.zip)

**Allure Commandline installations**
![Allure Commandline installations](https://cloud.githubusercontent.com/assets/7508122/11806244/7375e9e2-a31a-11e5-9d5f-d0df60704679.png)

**Post-build Actions**
![Post-build Actions](https://cloud.githubusercontent.com/assets/7508122/11806388/5690b068-a31b-11e5-9c88-85fbf2229b26.png)

Thanks

**Comment by baev** [comment]
@poohpeer thanks for the report. Could you please move your issue to related tracker https://github.com/jenkinsci/allure-plugin/issues ?
