### ISSUE TITLE
TestNG adaptor BUILD FAILURE [RUS]

### ISSUE THREAD

**Issue by 4el** [allure-framework/allure-core#719]
![image](https://cloud.githubusercontent.com/assets/16185026/11839668/69fb100c-a411-11e5-9208-ee8d5022e3cb.png)
![image](https://cloud.githubusercontent.com/assets/16185026/11839746/11365ae8-a412-11e5-955c-02f5cf4df252.png)

**Comment by vania-pooh** [comment]
А зачем компилировать руками, если можно взять готовую зависимость из [Maven Central](http://mvnrepository.com/artifact/ru.yandex.qatools.allure/allure-testng-adaptor/1.4.19)?

**Comment by 4el** [comment]
Чтобы не искать каждую готовую зависимость отдельно. Куда поместить jar файл?

**Comment by vania-pooh** [comment]
JAR кладется в classpath. Дальше TestNG через SPI подтягивает listener. Но там не один jar, а еще зависимости.

**Comment by 4el** [comment]
Я пробовал прописать зависимость сначала, файл подтянулся из репозитория и выдал ту же ошибку. Если я скачал отдельно именно этот файл, то думаю ничего не выйдет снова.

**Comment by 4el** [comment]
В процессе установки прогоняются какие-то тэсты, большинство из которых не проходят.

![image](https://cloud.githubusercontent.com/assets/16185026/11866183/2cdda260-a4cb-11e5-9104-2753408d7509.png)

В интернете ничего по этому поводу.

**Comment by vania-pooh** [comment]
Так, про падения тестов мы посмотрим. А вы лучше посмотрите на пример: https://github.com/allure-examples/allure-testng-example

**Comment by vania-pooh** [comment]
@baev: возможно под Винду или Java 8 не собирается.

**Comment by 4el** [comment]
Посмотрел пример, репорт удалось загрузить, только в Firefox. В хроме выдало такую ошибку:
![image](https://cloud.githubusercontent.com/assets/16185026/11869562/988eaf38-a4e2-11e5-8d46-1ca99e9e9958.png)

Были так же проблемы с jetty, вылетает 503 ошибка сервера. Но это думаю не ваша проблема.

**Comment by vania-pooh** [comment]
По поводу Chrome: http://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome/24002146#24002146

**Comment by 4el** [comment]
Спасибо, жду вашего решения насчет проблемы с установкой.

**Comment by lanwen** [comment]
Привет. Этот трекер англоязычный, т.к. аллюром пользуются не только в СНГ.
Для русскоязычных вопросов стоит: 
- Указывать заголовок на английском с пометкой (RUS)
- Задавать вопрос на русскоязычном stackoverflow (можно на трекере следуя предыдущему пункту давать ссылку на вопрос)

**Comment by 4el** [comment]
Пробовал билдить плагины по отдельности с командой '-rf'. Некоторые из оставшихся скомпилировались успешно. Проблемными остаются:
- allure-testng-adaptor
- allure-report-data
- allure-commandline

Во всех трех случаях возникает ошибка MojoFailureException при прогоне тестов.

**Comment by vania-pooh** [comment]
Для сборки нужно, чтобы в системы был phantomjs. У вас он есть?

**Comment by 4el** [comment]
Да, он установился

**Comment by 4el** [comment]
Пробовал билдить с JDK 7, с таким же исходом.

**Comment by 4el** [comment]
Есть ли возможность получить готовый архив с уже скомпилированным кодом версии 1.4.x под win7x32?

**Comment by baev** [comment]
@4el привет

> Чтобы не искать каждую готовую зависимость отдельно. Куда поместить jar файл?

Это джава. В процессе сборки ты также получишь jar. И все равно придется отдельно искать и подключать все необходимые зависимости. Для облегчения этого процесса люди придумали Ant, Maven и много других билд систем.

> Я пробовал прописать зависимость сначала, файл подтянулся из репозитория и выдал ту же ошибку. Если я скачал отдельно именно этот файл, то думаю ничего не выйдет снова. С maven познакомился только вчера, было бы приятно читать что либо по проще.

Я не вижу никакой ошибки. На скриншотах я вижу, что упала сборка allure-core по понятным причинам. 

> Спасибо, жду вашего решения насчет проблемы с установкой.

Нет никаких проблем с установкой, есть две проблемы в тестах (связяанные кст с багом в самой джаве), и известный баг с allure-commandline

> В процессе установки прогоняются какие-то тэсты, большинство из которых не проходят.

На данный момент в allure-core около 500 тестов (475 юнит тестов + интеграционные), у меня под win10 упало около 10 (включая интеграционные)


Ошибки я нашел, они в коде тестов (для allure-testng-adaptor и allure-reprot-data). Вот коммиты с исправлениями e1a9176741dcdf00760424bf574012ac907cb71e и a623127d40a00e171c96347ffc7f3ddad6c4ce60. С allure-commandline это известная бага (например, https://github.com/allure-framework/allure-teamcity-plugin/issues/36 - она же). Я все исправил, сейчас тестирую. До конца года будет хотфикс 1.4.20. Вообще, я не понимаю, зачем тебе нужно билдить проект. Если очень хочется, прям сейчас можно использовать -DskipTests=true. Это поможет. Еще все должно работать, если билдить core в директории, в пути к которой нет пробелов. Например, *C://projects*

> Есть ли возможность получить готовый архив с уже скомпилированным кодом версии 1.4.x под win7x32?

Это [джава](https://ru.wikipedia.org/wiki/Java). Все артефакты для всех версий доступны в Maven Central. Например, [allure-testng-adaptor](http://mvnrepository.com/artifact/ru.yandex.qatools.allure/allure-testng-adaptor). Выбираешь нужную версию, там есть инструкция как подключить к [Maven Ivy Grape Gradle Buildr SBT Leiningen] и ссылка **Download ( JAR )**. На той же странице можно найти секцию *Compile Dependencies*, в которой указан список необходимых зависимостей.

**Comment by baev** [comment]
@4el спасибо за репорт

проблемы с тестами пофиксил, для allure-commandline завел отдельный тикет https://github.com/allure-framework/allure-core/issues/725
