### ISSUE TITLE
Redesign allure-face

### ISSUE THREAD

**Issue by just-boris** [allure-framework/allure-core#721]
We have been using Allure almost for two years. Now it is time to make a face-lift. Now we are working on version 1.5, it will be released with current face. But now I started work on new face wich will be released in 1.6.

It will not be a significant change of the project structure. We are going to keep all current interfaces and tabs, such as Defects, xUnit, Behaviours and others. We hope you'll enjoy that change, that Allure will keep having modern UI.

This change is aimed to make the code more maintainable. Allure-report-face module will move from Maven plugins to Webpack. Also, now we are using Angular 1.4 which is deprecated in favor of Angular 2.0. However, the next version of Angular doesn't seem a good framework for us. So we have chosen Marionette. I have created a simple project based on new technology stack: https://github.com/just-boris/allure-new-web.

Since we are working at Yandex, we want to fit in our company style. That means that we are moving to [bem-components](https://en.bem.info/libs/bem-components/v2.4.0/showcase/) instead of Bootstrap. This framework also has stuck and doesn't resolve our needs. I was already used in project example and some our internal projects. Recently it has been open-sourced, so we can use it in the Allure.

Of course this, change will affect our plugin system. So, use plugins for 1.5 carefully. While we will be moving built-in plugins, we will make migration instructions, just be aware, that plugins for 1.5 didn't intend to use for a long time.

I'll be woking on some feature-branch and I will post progress updates here. Any comments and suggestions are welcome!

To do list:

* [x] Behaviours tab
* [x] Overview tabs and widget API for plugins
* [x] Graph tab
* [x] Timeline tab (this tab, as well as graphs, are based on D3 and I am not going to change it, so it will be kind of easy)
* [x] Keyboard navigation on tables
* [x] Status switcher for testsuites
* [x] Pane overlay to immediately come back
* [x] Show test case properties
* [x] Draggable widgets on overview
* [x] Collapsible sidebar
* [x] Sortable table columns
* [x] Tooltips on chart
* [x] Find a way to add localizations
* [x] Add color mark to status switcher buttons instead of colored text
* [ ] Add some insights about plugin API and migration guide from current

**Comment by ctapobep** [comment]
>Since we are working at Yandex, we want to fit in our company style. 
I think for Yandex it'll be more beneficial if the tool looks nice. Hopefully it won't get worse just because of patriotic feelings :)

**Comment by just-boris** [comment]
This story really needs some pictures. This is what I got at this moment.
![image](https://cloud.githubusercontent.com/assets/812240/11935503/326499a4-a819-11e5-8df2-1d23cad931ee.png)

**Comment by vania-pooh** [comment]
I would say that this is a cosmetic change and not about total redesign. If Bootstrap is really outdated then let's proceed with the new stack.

**Comment by just-boris** [comment]
Pane animation 2.0, fixed and improved :princess: 
![ezgif-3777140533](https://cloud.githubusercontent.com/assets/812240/11978039/5e8cc1ec-a999-11e5-8082-a1f3efc80228.gif)

**Comment by lanwen** [comment]
@just-boris new animation don't look like improved...:)

**Comment by just-boris** [comment]
well. That means I made so little fix, that you can't even notice it. At least I haven't broken anything.

**Comment by just-boris** [comment]
Now iframe attachment display perfectly fits into the pane.
![image](https://cloud.githubusercontent.com/assets/812240/12003730/b8fe7d6a-ab3c-11e5-9572-7f2231cda86b.png)

**Comment by just-boris** [comment]
Now I am going to work on expanded pane state.

**Comment by just-boris** [comment]
Also, I want to get rid of the heading. it gives more vertical space and allow to make less scrolling.
![image](https://cloud.githubusercontent.com/assets/812240/12003929/f22a8cf2-ab44-11e5-8a21-1e7cfc0c585b.png)

As you can see, there is a "collapse" button, so you will have collapsed view that you have now.

**Comment by lanwen** [comment]
@just-boris think word "Collapse" is unnecessary 
also stats is too bright

**Comment by just-boris** [comment]
ok. I will fix it

**Comment by just-boris** [comment]
I finish this year with the following view:

![image](https://cloud.githubusercontent.com/assets/812240/12052503/c6af6e14-af20-11e5-959e-687e19adf8e2.png)

Now report has almost all existing features, except the Behaviors and Graphs tab, but other tabs are already to use, because they made from the same set of blocks.

See you next year and I will go on.
:christmas_tree: :santa:

**Comment by baev** [comment]
@just-boris :+1:

**Comment by just-boris** [comment]
Well, I am going on. And now I have a list of things to do before publishing this version:

* [ ] Behaviours tab
* [ ] Overview tabs and widget API for plugins
* [ ] Graph tab
* [ ] Timeline tab (this tab, as well as graphs, are based on D3 and I am not going to change it, so it will be kind of easy)
* [ ] Collapsible sidebar
* [ ] Sortable table columns
* [ ] Add some insights about plugin API and migration guide from current

**Comment by just-boris** [comment]
Published interactive preview of new design: http://catatron.com/allure/#defects

You can try and suggest something. Now it is perfect time for it

**Comment by ctapobep** [comment]
Yellow color of the buttons (when pressed) look worse than previously imho.

**Comment by just-boris** [comment]
All tabs are done: http://catatron.com/allure/
 
There are a lot of little tasks to do (@ctapobep, of course, I will think about your comment), but we are going to merge it to master and publish new release very soon. So you will be able to try new face with your tests!

**Comment by just-boris** [comment]
:fire: Sidebar is now collapsible!
![ezgif-1404371513](https://cloud.githubusercontent.com/assets/812240/12418085/ec5d36c6-bebd-11e5-82af-c6310f9b4694.gif)

**Comment by baev** [comment]
@just-boris I kinda don't like pack name in side bar at all

**Comment by baev** [comment]
+ there is no need to show version, data size etc in case your side bar is collapsed. How do you suppose to use it for?

**Comment by just-boris** [comment]
1. Les't move pack name to overview widget. It will be look nice here instead of dummy `Test run`
2. If you are interested in this info, just open it. What is the problem. Also, we can move it to widget as well

The main goal is achieved now. 99% of the screen space was given to panes with information. I don't want to move it back with extra panels and menus.

**Comment by lanwen** [comment]
:+1: for pack name instead of  "Test Run" and remove it from sidepanel

**Comment by just-boris** [comment]
Latest version is now likely available on our CI server: http://ci.qatools.ru/job/allure-core_pull-request/Allure_report/index.html

It is automaticaly rebuilt after each my commit.

**Comment by lanwen** [comment]
Please hide numbers when it doesn't visible in the bar (see the purple)

**Comment by just-boris** [comment]
I am thinking about min-width for bar segments to fit all content.
It seems better than keep some parts of data invisible.

**Comment by ehasenkamp** [comment]
The new UI is looking good.  I've a suggestion about the stacktrace area... maybe it's just me, but I'd like to be able to click anywhere in that area to expand the stack trace (instead of moving the mouse to the right side of the report).  To signify the area is clickable, maybe just highlight it on mouse hover; similiar to how the tests and suites are highlighted.

Just a thought.  :)

**Comment by just-boris** [comment]
@ehasenkamp good point. Okay, I'll try to do it.

**Comment by just-boris** [comment]
Tested new face in a conjunction with [wdio-allure-reporter](). It looks like a real example of tests.

The result looks nice:

![image](https://cloud.githubusercontent.com/assets/812240/12642564/a0462174-c5c7-11e5-91d1-3a7edf45f728.png)

**Comment by just-boris** [comment]
@ehasenkamp I considered, that it would be hard to select some text from failure message if any click opens the stack trace.

But I have implemented it on double click. If you want to see the stack trace, just double click on failure message. Pretty instant.

**Comment by lanwen** [comment]
:-1: for me for the new design. Something good, but most of controls and colors looks worse than prev version. This design is not about test report. You shouldn't just copy yandex colors, you should think about role of blocks in this interface.

But im :+1: for merging this because of code looks definately  great and allows to change design without much effort

**Comment by tk8817** [comment]
When might we see this merged? Is there any recent update, the changes look great!

**Comment by baev** [comment]
I'll merge it ASAP

2016-04-06 19:03 GMT+03:00 Justin Watts <notifications@github.com>:

> When might we see this merged? Is there any recent update, the changes
> look great!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/allure-framework/allure-core/issues/721#issuecomment-206442308>
>



-- 
С уважением,
Баев Дмитрий

**Comment by anuvratashu** [comment]
Hi ,

I love this report and has been using it in my projects. However, just wanted to know if there is any way i can change the labels like 'Test case' to 'Test Step'. Why this is needed? because in our project we are using the jasmine framework and each describe is a Test case for us and Each IT function is a test step. However, in report the test cases comprises of IT function, so it would be little easy for management to understand that these are steps and not test cases executed.

Hope you understand my question?

**Comment by SGDSmith** [comment]
@anuvratashu - You can edit the translations file to change Test cases to whatever you want (I assume you meant the text above the list of cases). 
If you are using English then the file can be located in 'src/translations/en.json' and the build the project

**Comment by anuvratashu** [comment]
Hi Smith,

I am not seeing the Translations folder and en.json file. 

![image](https://cloud.githubusercontent.com/assets/14295329/24840212/b5809f66-1d86-11e7-858c-03ea0fe65d4c.png)

**Comment by just-boris** [comment]
Hello, @anuvratashu.

I'd say that the goal that you want to achieve is rather incorrect. [Jasmine documentation](https://jasmine.github.io/edge/introduction#section-Standalone_Distribution) gives you the strict definition what is test suite and how it is required. Allure follows this definition and maps test result by the defined logic and we do not expect this logic to be customized.

Instead of trying to hack the system and rename some parts of Allure UI, I'd rather suggest you to revisit your tests structure and define test cases as test cases, and use `allure.createStep` method to define actual test steps.

--
⚠️ Moderator warning: this is completely off-topic for this thread.
@anuvratashu if you want to reply, please do it an a separate issue. Therefore, I lock this thread in order to protect other people from unnecessary notifications.
