### ISSUE TITLE
Generation error of allure reports with allure-cli (RUS)

### ISSUE THREAD

**Issue by igreench** [allure-framework/allure-core#722]
Поставил <b>jre1.8.0_66</b>, <b>NUnit 2.6.3</b>. В <b>NUnit 2.6.3</b> залил <b>allure-nunit2-0.2.1</b>. Собрал <b>dll</b>-ку в <b>VS2012</b> на <b>C#</b>. 

Запускаю <b>allure-commandline</b> версии <b>1.4.19</b> через <b>bat</b>-файл:

<blockquote>set ASSEMBLIES_DIR="D:\Coding\task\testing\1"<br>
set NUNIT_HOME="C:\Program Files (x86)\NUnit 2.6.3"<br>
set ALLURE_CLI_HOME="D:\Coding\task\testing\allure-commandline"<br>
set JAVA_HOME="C:\Program Files\Java\jre1.8.0_66"<br>
set NGINX_HOME="D:\Program Files\nginx-1.9.9"<br>
set OUTPUT_DIR="D:\Coding\task\testing\test-results"<br>
%NUNIT_HOME%\bin\nunit-console.exe %ASSEMBLIES_DIR%\allure-testing.dll /framework=net-4.0<br>
%ALLURE_CLI_HOME%\bin\allure.bat generate %OUTPUT_DIR% -o %NGINX_HOME%\html<br></blockquote>

И получаю ошибку:

<blockquote>Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationExcepti
on: Could not find any allure results<br>
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)<br>
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)<br>
        at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)<br>
←[0;31mERROR: ←[mCommand aborted due to exception org.apache.commons.exec.Execut
eException: Process exited with an error: 1 (Exit value: 1).</blockquote>

Вот XML-файл (TestResult.xml):

<blockquote>&lt;?xml version="1.0" encoding="utf-8" standalone="no"?&gt;<br>
&lt;!--This file represents the results of running a test suite--&gt;<br>
&lt;test-results name="D:\Coding\task\testing\1\allure-testing.dll" total="1" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2015-12-18" time="08:02:28"&gt;<br>
  &lt;environment nunit-version="2.6.3.13283" clr-version="2.0.50727.5485" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="D:\Coding\task\testing" machine-name="ROOT" user="superuser" user-domain="root" /&gt;<br>
  &lt;culture-info current-culture="ru-RU" current-uiculture="ru-RU" /&gt;<br>
  &lt;test-suite type="Assembly" name="D:\Coding\task\testing\1\allure-testing.dll" executed="True" result="Success" success="True" time="0.081" asserts="0"&gt;<br>
    &lt;results&gt;<br>
      &lt;test-suite type="Namespace" name="allure_testing" executed="True" result="Success" success="True" time="0.057" asserts="0"&gt;<br>
        &lt;results&gt;<br>
          &lt;test-suite type="TestFixture" name="Class1" executed="True" result="Success" success="True" time="0.053" asserts="0"&gt;<br>
            &lt;results&gt;<br>
              &lt;test-case name="allure_testing.Class1.firstSimpleTest" executed="True" result="Success" success="True" time="0.038" asserts="0" /&gt;<br>
            &lt;/results&gt;<br>
          &lt;/test-suite&gt;<br>
        &lt;/results&gt;<br>
      &lt;/test-suite&gt;<br>
    &lt;/results&gt;<br>
  &lt;/test-suite&gt;<br>
&lt;/test-results&gt;</blockquote>

Ковырялся, ковырялся, так и не понял, то ли я дурак, то ли лыжи не едут.

**Comment by vania-pooh** [comment]
@igreench видно, что CLI не находит XML файл. У Java проблемы с Windows путями - они как-то нетривиально вводятся. Можно попробовать такое изменение:
```
set OUTPUT_DIR="D:/Coding/task/testing/test-results"
```

**Comment by igreench** [comment]
@vania-pooh попробовал, не работает. Вообще, не должно быть с этим проблем. Мне казалось, что косяк в генерируемом XML, но раз вы об этом не написали, то наверное с ним всё хорошо. Я пробовал найти код, в котором парсится XML, но не нашел.

Знаю, что был баг с местом, откуда вызывается генератор отчета allure. Вроде как нужно вызывать не из директории с XML. Но я по всякому пробовал - всё равно вылетает ошибка о ненахождении XML.

**Comment by vania-pooh** [comment]
На всякий случай можно попробовать проверить XML по [схеме](https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd).

**Comment by lanwen** [comment]
Привет. Этот трекер англоязычный, т.к. аллюром пользуются не только в СНГ.
Для русскоязычных вопросов стоит: 
- Указывать заголовок на английском с пометкой (RUS)
- Задавать вопрос на русскоязычном stackoverflow (можно на трекере следуя предыдущему пункту давать ссылку на вопрос)

**Comment by baev** [comment]
@igreench привет

*TestResult.xml* - это xml в фомате xUnit, мы не умеем по ней строить отчет. Аллюровские файлы имеют в названии суффикс *-testsuite.xml*, и лежат в папке, указанной в **%NUnit_installation_directory%\bin\addins\config.xml#results-path**. См. пункт 5 https://github.com/allure-framework/allure-nunit2
