### ISSUE TITLE
Tests showing as twice

### ISSUE THREAD

**Issue by fropcorn-ravi** [allure-framework/allure-core#731]
![untitled](https://cloud.githubusercontent.com/assets/16422124/12232455/abf587ee-b884-11e5-863e-c5931ecfcb41.png)

Hello i have an issue for getting the reports where i am using giving parameters in *testng.xml* to run the same test class twice for different devices. everything is going fine but in the report all the test cases are showing twice for each device.
 my *testng.xml* file is as follows 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="testExecution" parallel="methods" thread-count="2">
  <test name="SamsungS4">
      <parameter name="device" value="Samsung5.1.1"></parameter>
   	  <parameter name="deviceName" value="a01b27a8"></parameter>
      <parameter name="version" value="5.1.1"></parameter>
    <classes>
      <class name="testsuite.testExecution"/>
    </classes>
  </test> <!-- Test -->
  <test name="Nexus">
      <parameter name="device" value="Nexus6.0.1"></parameter>
   	  <parameter name="deviceName" value="03829155439cb1e8"></parameter>
      <parameter name="version" value="6.0.1"></parameter>
    <classes>
      <class name="testsuite.testExecution"/>
    </classes>
  </test> <!-- Test -->
</suite> <!-- TestConfig -->
```

**Comment by volkovs** [comment]
Hello. IMO it is expected behavior. Report shows as many test cases as many executions there were. It doesn't matter whether the test was parametrized or not. So, if test passed on one device and failed on another, there will be two test cases with according statuses. You can also parametrize test case name with parameters value.

**Comment by fropcorn-ravi** [comment]
Thank you for your reply , I will tell the whole scenario . I am using Appium with help of selenium grid and I am giving device parameters in testng.xml the screenshot I attached is only one test case running in both the devices. But it's showing same test cases many number of times.

**Comment by volkovs** [comment]
@fropcorn-ravi could you please provide testng.xml once more?

**Comment by fropcorn-ravi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16422124/12262319/341310ba-b94d-11e5-8c9a-282291529d43.png)

**Comment by fropcorn-ravi** [comment]
i have checked the xml generated by allure report. test cases were showing twice for each device, i have attached the pom xml in the attachement , could you please check and tell where i have done a mistake.
[pom.txt](https://github.com/allure-framework/allure-core/files/88721/pom.txt)

**Comment by modnarlp** [comment]
Hello. 

I have the same situation as @fropcorn-ravi. In my pom.xml i defined suiteXmlFile in which i defined java class with method marked with @Factory annotation. Every time i invoke 
mvn clean test 
from command line it show me that 3 tests were performed but in report(mvn site) i see twice as much.

[FactoryClass.txt](https://github.com/allure-framework/allure-core/files/95922/FactoryClass.txt)
[runner.txt](https://github.com/allure-framework/allure-core/files/95916/runner.txt)
[pom.txt](https://github.com/allure-framework/allure-core/files/95917/pom.txt)

**Comment by yulia-nechaeva** [comment]
Hey guys, look at these lines in your pom.xml:

    
    <properties>
        <property>
                <name>listener</name>
                <value>ru.yandex.qatools.allure.testng.AllureTestListener</value>
        </property>
    </properties>

Since you are using TestNG version 1.4.* you don't need these properties in the pom anymore. Looks like listener adds twice in that case and that's why tests are showing twice in report. 

So, report shows correctly after deleting that piece of code from pom.xml.

**Comment by modnarlp** [comment]
Hello, thanks a lot for your answer. You are absolutely right with that additional AllureTestListener in pom.xml cause the problem.

**Comment by baev** [comment]
@yulia-nechaeva :+1: 

http://stackoverflow.com/questions/25161075/allure-framework-testng-adapter-generates-duplicate-xml-files

**Comment by fropcorn-ravi** [comment]
Thanks a lot , you were right....

Ravi Kiran
Software Development Engineer in Test 
Fropcorn

**Comment by fdPoornima** [comment]
Hi @fropcorn-ravi  : How were you able to insert the details of the devices in the report i.e: Nexus, version etc. Also, for me the second device execution is shown as a retry, is this working fine for you
