### ISSUE TITLE
Support multiple levels of user stories

### ISSUE THREAD

**Issue by buzdin** [allure-framework/allure-core#732]
In our projects we have the following requirement hirarchy

Main Requirement -> Epic -> User Story -> Task

Tests are mapped to User Stories, but for reporting purposes it would be very helpful to see the full requirement hierarchy.

The request is to support nested requirements in Allure and show them as several level of expandable items in Behaviors tab. The trick is that higher level requirements will not have test cases attached directly to that. Any ideas how to implement that? Plugin API may be sufficient, requirements are coming from a third-party system and it is not necessary to show full path in annotation. So the source code would still have just one user story and the rest should be fetched somehow.

**Comment by baev** [comment]
@buzdin thanks for suggestion! 

We are kinda going to implement such feature soon. So stay turned.

**Comment by baev** [comment]
Done in Allure 2
