### ISSUE TITLE
Error: no main manifest attribute when CLI tool to generate report version 1.5.0-RC1

### ISSUE THREAD

**Issue by bubanoid** [allure-framework/allure-core#736]
I have installed the latest version of Allure CLI and could not generate a report. My alluredir with xml-files was generated with **pytest-allure-adaptor v.1.7.0** and is attached.
[alluredir.zip](https://github.com/allure-framework/allure-core/files/90381/alluredir.zip)

It seems to be an issue:

    no main manifest attribute, in /home/andriy/.allure/bundles/1.5.0-RC1/allure-bundle.jar
    ERROR: Command aborted due to exception org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1).

**Comment by baev** [comment]
@bubanoid hi!

`allure-cli` is deprecated, so you should use `allure-commandline` instead. See http://wiki.qatools.ru/display/AL/Allure+Commandline

**Comment by bubanoid** [comment]
My system is `Ubuntu 15.10` (not Trusty, not Precise). My system doesn't fit the requirements for installation `allure-commandline` presented these. Is there a way to install `allure-commandline` into my system? [Here](http://stackoverflow.com/questions/34772906/unable-to-install-allure-cli-on-ubuntu-15-10) is my question on stackoverflow.

**Comment by baev** [comment]
So I answered your question at SO

btw:

To install Allure you need to do the following steps:

* Download the latest version as zip archive from https://github.com/allure-framework/allure-core/releases/latest.
* Unpack the archive to allure-commandline directory.
* Navigate to bin directory.
* Use allure script to run commandline.

So you can also add unpacked directory to the **PATH** and then use allure command as well.

**Comment by bubanoid** [comment]
solved

**Comment by baev** [comment]
@bubanoid :+1:

**Comment by Pranab078** [comment]
Hi Baev, I am totally new to this Allure FrameWork..
I need help on setting up the Framework.So i need help. I am using testng Framework with Allure.In testNG class , i used some of the Allure Parameters, like @Steps,@Attachments,@Severity etc etc.And i have included ->java -javaagent:"C:\selenium\libs\allure\aspectjweaver-1.8.3.jar" org.testng.TestNG C:\Selenium\testngKM.xml -d C:\GTFR\Log\fetests also for Generating Reports. But my problem is that How to get the Allure Reports,What should i ido to get the Reports in Allure.

Thanks in Advace
