### ISSUE TITLE
[Question] Cant run allure.bat showing error

### ISSUE THREAD

**Issue by dangprady** [allure-framework/allure-core#737]
Steps which are mention here [window section] http://wiki.qatools.ru/display/AL/Allure+Commandline are either not update or I can't understand fully.

It says navigate to bin directory. It must be sitting pretty somewhere as I can't find this directory anywhere in downloaded zip.

If it gets generated after following certain steps then those are not mentioned in above link.

Kindly update the documentation as I can see in allure.bat which I found in allure-commandline\src\main instead of bin directory statements likes if not exist "%ALLURE_HOME%\bin\allure.bat"

I assume this is case of one step from installation missing which is considered as self-understood. Kindly update installation steps if that's the case.

I am facing ERROR: <directory> is not a valid allure commandline directory If I try to run allure.bat from main\scripts directory

**Comment by baev** [comment]
@dangprady hi!

You need to download `allure-commandline.zip` or `allure-commandline.tar.gz` from [releases](https://github.com/allure-framework/allure-core/releases) page. [Link](https://github.com/allure-framework/allure-core/releases/download/allure-core-1.4.20/allure-commandline.zip) to download the latest 1.4.20 commandline.

Then you need to unpack it. The archive has the following structure:
* **app**
* **bin**
* **conf**
* **lib**
* **plugins**

So you need to add this directory to `PATH`, then you will able to run `allure` command.

**Comment by baev** [comment]
closed as no response

**Comment by debashaR** [comment]
Hi baev,
I am facing similar issue while installing in Windows 7, already I have done everything mentioned above but unable to succeed with allure.bat, please respond

**Comment by debashaR** [comment]
Using javac 1.8.0_102 also mentioned in PATH. But after running allure.bat still getting below error mesage:

Could not find java implementation: try to set JAVA_HOME, JRE_HOME or add java t
o PATH.

Downloaded allure-commandline.zip from https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.23.HOTFIX1
