### ISSUE TITLE
[Suggestion] Log step description

### ISSUE THREAD

**Issue by ZaziroZ** [allure-framework/allure-core#739]
Hi all,
Is there any possibility to implement tunable logging of step descriptions into standard console? Offentimes, this may be useful.

**Comment by baev** [comment]
In general you can use the experimental lyfecyclelistener API. There is an example how to implement the logging of step descriptions https://github.com/allure-examples/allure-java-lifecyclelistener-example

**Comment by ZaziroZ** [comment]
A good idea, thanks! But will this work for TestNG (provided all necessary changes in pom.xml made)?

**Comment by baev** [comment]
> But will this work for TestNG

Yep. All you need is implement `LifecycleListener` somewhere in your project and register it as [SPI](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html) service

**Comment by ZaziroZ** [comment]
Thank you Dmitry, it worked!

**Comment by baev** [comment]
@ZaziroZ this API is an experimental one, so it can be changed in next releases. See https://github.com/allure-framework/allure-core/issues/735
