### ISSUE TITLE
Question on Log functionality inside the Allure Report

### ISSUE THREAD

**Issue by jsudhi** [allure-framework/allure-core#747]
Hello Friends, 

Before configuing allure reporting with my webdriver/java tests, I was using log4j to write lot of log messages inside the test case method and library methods. There being  written into simple text file. Is there a way to print them into the allure report against each test case itself ? 

I have seen some refrences to @Step. But I understand that it can be used just as annotation on top of the library methods but NOT inside the methods. 

Please correct me if I am wrong. Any help to configure logs into the reports would be greatly appreciated.

-Sudhi

**Comment by ostap-oleksyn** [comment]
You can create a simple logger class like this:

```
public final class LogUtil {

    private LogUtil() {
    }

    @Step("{0}")
    public static void log(final String message){
        //intentionally empty
    }
}
```

Then you can just call the log() method everywhere you want, pass a message to it and it will be added to your allure report.

**Comment by jsudhi** [comment]
I could get this resolved using :

` @Step("{0}")
	public static void log(String message) {
		logger.info("Logged to allure: " + message);
		LIFECYCLE.fire(new StepStartedEvent(message));
		LIFECYCLE.fire(new StepFinishedEvent());
		String logPrefix = "|" + StringUtils.repeat("_", stackTraceDepth() - 3);
		Reporter.log(logPrefix + message);
	}`
