### ISSUE TITLE
Character limit for @Step

### ISSUE THREAD

**Issue by mctaggartm** [allure-framework/allure-core#748]
Hi, there seems to be a 120 character limit when using the @Step annotation. Can this be increased?

**Comment by baev** [comment]
@mctaggartm hi

you can use property `allure.max.title.length` to change character limit.

**Comment by mctaggartm** [comment]
Thanks for the quick response.

Is this used under configuration/properties? Can you provide an example
please?

Mark

**Comment by mctaggartm** [comment]
Does this work for @Step?

**Comment by baev** [comment]
> Does this work for @Step?

yep

> Can you provide an example
> please?

An example if you use `maven-surefire-plugin` you can add such `systemProperty`:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <systemProperties>
            <allure.max.title.length>200</allure.max.title.length>
        </systemProperties>
        ...
    </configuration>
</plugin>
```

Or you can create an `allure.properties` file:

```
allure.max.title.length=200
```

and add it to classpath

**Comment by mctaggartm** [comment]
Thank you that worked !
