### ISSUE TITLE
Screen Shot mismatch in attachment

### ISSUE THREAD

**Issue by rajputswat** [allure-framework/allure-core#750]
in allure report ,Screen Shot does not match with Test.While running suite Screen shot of Test 'A' gets attached to Report of Test 'B' and  vice-versa .

**Comment by baev** [comment]
@rajputswat hi. Could you please give explain the problem in more details? Also the sample project to reproduce the problem is much appreciated

**Comment by rajputswat** [comment]
my project is based on Page Object model

My test class extends TestBase
TestBase Class contains BeforeMethod,Attachment,AfterMethod

 @BeforeMethod(groups = "horizontal", alwaysRun = true)
    public void setUp()
    {

        try
        {
            logger = LogFactory.getLog(this.getClass().getName());
          
        }

        catch (Exception e)
        {
            e.printStackTrace();
        }
        //  headerPage.checkCity();


    }

    @Attachment
    public byte[]screenShot()
    {
        return ((TakesScreenshot)driver).getScreenshotAs(OutputType.BYTES);
    }

    @AfterMethod(groups = "horizontal", alwaysRun = true)
    public void tearDown()
    {
try
{

           
            screenShot();
                   driver.closeApp();
            driver.quit();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

**Comment by baev** [comment]
duplicate https://github.com/allure-framework/allure-core/issues/706
