### ISSUE TITLE
How to share allure reports

### ISSUE THREAD

**Issue by anarwal** [allure-framework/allure-core#755]
After running tests I want to share the allure report with my team members, is there a way to send them an email of the report, I saw earlier issues on this but they were using TestNG, I use webdriver IO with Mocha.

Also I want to upload screen shots of failures with allure report, how can I do that?

**Comment by vania-pooh** [comment]
@anarwal how about just zipping allure report folder? All paths are relative.

**Comment by anarwal** [comment]
@vania-pooh So every time should I be zipping the folder and sending it over?

**Comment by vania-pooh** [comment]
@anarwal Any CI server can do this for you, too.

**Comment by baev** [comment]
closed due to mo activity

**Comment by hemanthsridhar** [comment]
@anarwal  how to send it via jenkins?
