### ISSUE TITLE
v2.0 more suggestions

### ISSUE THREAD

**Issue by michaelDomingues** [allure-framework/allure-core#756]
Hi,

Excellent work in Allure! You got pretty awesome stuff here.

I read all the labelled `improvements` and would like to suggest some more:

- In Jenkins plugin, add an email system to send a **.html**, **.pdf**, (something) to a recipients list configured. I'm taking advantage of a feature request already made to export to **.html** and over add the email. With an automation system receiving the report by email would be 5*

-  How its gonna be the customise report thing ? There are some charts I really want to add to the report, like a pie chart but filter by browser and not the PASSED/PENDING/BLOCKED/... tests..
As this one I want a lot more but simple things. To make my own `kpis`. Will I be able to to this ? 

If not please consider adding this kind of stuff, at least the possibility to make charts easily by data filter.

Many thanks

**Comment by just-boris** [comment]
I don't know what to answer to the first suggestion, it should be some Jenkins specific thing. I know that we have some plans to make an email template that can be sent from your testing system.

About the second question: we almost finished global redesign. After it will have been released, you will can to add your own tabs, custom blocks to test case view and widgets to main dashboard tab. Documentation with public API for it are also expecting to come.

**Comment by baev** [comment]
> In Jenkins plugin, add an email system to send a .html, .pdf, (something) to a recipients list configured. I'm taking advantage of a feature request already made to export to .html and over add the email. With an automation system receiving the report by email would be 5*

https://github.com/jenkinsci/allure-plugin/issues/21

**Comment by baev** [comment]
@michaelDomingues btw, thanks for suggestion!
