### ISSUE TITLE
mvn site not generating results directories

### ISSUE THREAD

**Issue by maheshbedampeta** [allure-framework/allure-core#758]
With mvn site I'm getting below error,

[INFO] Generating "Allure" report    --- allure-maven-plugin:2.2
[INFO] Report Version: 1.4.16
[INFO] Results Pattern: **/allure-results
[INFO] Found [0] results directories by pattern [**/allure-results]
[INFO] Found [0] plugins
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.412 s
[INFO] Finished at: 2016-03-08T17:50:09+05:30
[INFO] Final Memory: 12M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:si
te (default-site) on project Ancestry_STAGE_maven: Error during page generation:
 Error rendering Maven report: Can't find any results directories by pattern [**
/allure-results] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

And below is Report generating snippet in the pom.xml

```
<reporting>
		<excludeDefaults>true</excludeDefaults>
		<plugins>
			<plugin>
				<groupId>ru.yandex.qatools.allure</groupId>
				<artifactId>allure-maven-plugin</artifactId>
				<version>2.2</version>
				<configuration>
					<outputDirectory>${basedir}/target/allure-reports/</outputDirectory>
					<allureResultsDirectory>${basedir}/target/allure-results</allureResultsDirectory>
				</configuration>
			</plugin>

		</plugins>

		<outputDirectory>${basedir}/site</outputDirectory>
	</reporting>
```

**Comment by vania-pooh** [comment]
@maheshbedampeta Allure results are generated during ```$ mvn test``` phase.

**Comment by maheshbedampeta** [comment]
@vania-pooh I'm unable to generate the Allure results during $mvn test phase also. Please help me out in getting the results

**Comment by vania-pooh** [comment]
@maheshbedampeta which test framework are you using? You need to add respective Allure adapter dependency to pom.xml.

**Comment by maheshbedampeta** [comment]
@vania-pooh I'm using TestNG framework. Yes infact I've added following adapter dependency to pom.xml.

```
<dependency>
			<groupId>ru.yandex.qatools.allure</groupId>
			<artifactId>allure-testng-adaptor</artifactId>
			<version>1.4.16</version>
			<exclusions>
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

**Comment by baev** [comment]
@maheshbedampeta at least you need to upgrade allure-maven-plugin to 2.5. Since 2.3 the plugin configuration was changed, so see the docs http://wiki.qatools.ru/display/AL/Allure+Maven+Plugin

**Comment by maheshbedampeta** [comment]
@baev Hey thanks very much for the update. With the change you mentioned I can see the console with Build Success message with couple of warning messages as below.


[WARNING] Results directory for module <Project Name> not found.
[WARNING] Allure report was skipped because there is no results directories found.

As a result I'm not able to see any content in the report
![report](https://cloud.githubusercontent.com/assets/10337451/13635426/8ec6c460-e621-11e5-8da6-1b785501ace1.jpg)

**Comment by baev** [comment]
@maheshbedampeta could you please specify your project structure? Does `target/allure-resutls` folder exists in your tests module? What version of testNg are you use?

**Comment by maheshbedampeta** [comment]
@baev @vania-pooh Hey guys thanks for helping me out. I was using poor version of testng. I've updated it to latest and reporting is working great now.

**Comment by baev** [comment]
You are welcome

**Comment by Iamshubhk** [comment]
@baev and @vania-pooh  I am getting the same error my testNG and allure-maven-plugin version is latest but I am not able to generate allure html report.
My POM is:
<properties>
		<allure.version>1.4.16</allure.version>
		<aspectj.version>1.8.5</aspectj.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.13.3</version>
		</dependency>
		<dependency>
			<groupId>ru.yandex.qatools.allure</groupId>
			<artifactId>allure-testng-adaptor</artifactId>
			<version>1.4.16</version>
			<exclusions>
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-chrome-driver</artifactId>
			<version>2.53.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.53.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>3.15</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.15</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>2.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.15</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
					<argLine>
						-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
					</argLine>
					<suiteXmlFiles>
						<suiteXmlFile>testng.xml</suiteXmlFile>
					</suiteXmlFiles>
					<configuration>
						<webAppSourceDirectory>${project.build.directory}/site/allure-maven-plugin</webAppSourceDirectory>
					</configuration>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjweaver</artifactId>
						<version>${aspectj.version}</version>
					</dependency>
				</dependencies>
			</plugin>

			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<fork>true</fork>
					<executable>C:\Program Files\Java\jdk1.8.0_65\bin\javac</executable>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<reporting>
		<excludeDefaults>true</excludeDefaults>
		<plugins>
			<plugin>
				<groupId>ru.yandex.qatools.allure</groupId>
				<artifactId>allure-maven-plugin</artifactId>
				<version>2.5</version>
				<configuration>
					<resultsDirectory>allure-results</resultsDirectory>
					<reportDirectory>allure-report</reportDirectory>
				</configuration>
			</plugin>
		</plugins>
		<outputDirectory>${basedir}/site</outputDirectory>
	</reporting>
</project>

getting below error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.812 s
[INFO] Finished at: 2016-10-26T02:49:11+05:30
[INFO] Final Memory: 30M/379M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project netlok: Error during page generation: Error rendering Maven report: Could not generate the report: 'other' is different type of Path -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by PratapSingh09** [comment]
I m  using below Pom.xml but I m not able to get th ereport I am getting below warning 

[INFO] configuring report plugin ru.yandex.qatools.allure:allure-maven-plugin:2.5
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Generating "Allure" report    --- allure-maven-plugin:2.5
[INFO] Generate Allure report (aggregate) with version 1.5.2
[INFO] Generate Allure report to target/site/allure-report
[WARNING] Results directory for module Sample not found.
[WARNING] Allure report was skipped because there is no results directories found.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.864 s




<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.yandex.allure</groupId>
    <artifactId>Sample</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <allure.version>1.5.2</allure.version>
        <allure.maven.version>2.5</allure.maven.version>
        
        <allure.results_pattern>allure-results</allure.results_pattern>
    </properties>
    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-report-face</artifactId>
            <version>${allure.version}</version>
            <type>war</type>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.2.10.v20150310</version>
                <configuration>
                    <webAppSourceDirectory>target/site/allure-maven-plugin</webAppSourceDirectory>
                    <stopKey>stop</stopKey>
                    <stopPort>2299</stopPort>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>${allure.maven.version}</version>
               
                <configuration>
                    <resultsPattern>${allure.results_pattern}</resultsPattern>
                    <resultsDirectory>target/site/allure-results</resultsDirectory>
                    <reportDirectory>target/site/allure-report</reportDirectory>
                    <outputDirectory>${basedir}/site</outputDirectory>
                    
                </configuration>
            </plugin>
        </plugins>
    </reporting>
</project>



Can anyone please help me with this

**Comment by PratapSingh09** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.yandex.allure</groupId>
    <artifactId>Sample</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <allure.version>1.5.2</allure.version>
        <allure.maven.version>2.5</allure.maven.version>
        
        <allure.results_pattern>allure-results</allure.results_pattern>
    </properties>
    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-report-face</artifactId>
            <version>${allure.version}</version>
            <type>war</type>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.2.10.v20150310</version>
                <configuration>
                    <webAppSourceDirectory>target/site/allure-maven-plugin</webAppSourceDirectory>
                    <stopKey>stop</stopKey>
                    <stopPort>2299</stopPort>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>${allure.maven.version}</version>
               
                <configuration>
                    <resultsPattern>${allure.results_pattern}</resultsPattern>
                    <resultsDirectory>target/site/allure-results</resultsDirectory>
                    <reportDirectory>target/site/allure-report</reportDirectory>
                    <outputDirectory>${basedir}/site</outputDirectory>
                    
                </configuration>
            </plugin>
        </plugins>
    </reporting>
</project>

**Comment by vania-pooh** [comment]
```
[WARNING] Allure report was skipped because there is no results directories found.
```
Do you have XML files in ```target/allure-results```. Need to attach respective adapter for get it.

**Comment by baev** [comment]
https://github.com/allure-framework/allure1/issues/949

**Comment by PratapSingh09** [comment]
Now I am getting below consol message but with this empty result screenshot:

[INFO] --- maven-site-plugin:3.3:site (default-site) @ Sample ---
[INFO] configuring report plugin ru.yandex.qatools.allure:allure-maven-plugin:2.5
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Generating "Allure" report    --- allure-maven-plugin:2.5
[INFO] Generate Allure report (aggregate) with version 1.5.2
[INFO] Generate Allure report to C:\Sample\target\site/allure-maven-plugin
[INFO] Found results directory C:\Sample\target\allure-results
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.105 s
[INFO] Finished at: 2017-04-04T13:01:01+02:00
[INFO] Final Memory: 33M/356M


![image](https://cloud.githubusercontent.com/assets/17722170/24653759/72e54f10-1937-11e7-849e-ec71c95b6d32.png)

**Comment by PratapSingh09** [comment]
I have attached my project structure along woth pom.xml changes i did

**Comment by baev** [comment]
you need to serve the report due to security policy (an example using jetty maven plugin)

**Comment by PratapSingh09** [comment]
@baev  I did not get you exactly, Could you please explain it little bit bcz I am totally new to this allure report

**Comment by baev** [comment]
report is generated successfully but it using ajax to fetch report data. Due to security issues browser deny ajax requests to file system, so you need to serve the report using web server first. 

An example, you can install `allure-commandline` and use command `allure open path/to/report/directory` or jetty maven plugin (see https://github.com/allure-examples/allure-junit-example as an example) 

The related FAQ section: https://github.com/allure-framework/allure1/wiki/FAQ-and-Troubleshooting#i-see-nothing-when-opening-the-report-page-in-my-browser--access-denied-message

**Comment by PratapSingh09** [comment]
I am not able to invoke screenshot for failure scenario:
this is my project structure:

![image](https://cloud.githubusercontent.com/assets/17722170/24753391/3b962290-1ad2-11e7-9339-71f6db64964a.png)
 hooks.js:
var Cucumber = require('cucumber');
var fs = require('fs');
var conf = require('../conf').config;
var reporter = require('cucumber-html-reporter');
var report = require('cucumber-html-report');


var hooks = function () {
    "use strict";
    var jsonReports = process.cwd() + '/reports/json';
    var htmlReports = process.cwd() + '/reports/html';
    var targetJson = jsonReports + '/cucumber_report.json';
     var outputDir = './target/allure-results';



    this.registerHandler('BeforeFeature', { timeout: 10 * 1000 }, function (event) {
        return browser.get(conf.baseUrl);

    });
  this.After('Successfully Applied Hooks', function (scenario) {
        if (scenario.isFailed()) {
            browser.takeScreenshot().then(function (base64png) {
                var decodedImage = new Buffer(base64png, 'base64').toString('binary');
                scenario.attach(decodedImage, 'image/png');
                callback();
            }, function (err) {
                return callback(err);
            });
        }else{
        callback();
        }

    });

    var cucumberReportOptions = {
        source: targetJson,
        dest: htmlReports,
        name: 'cucumber_report.html',
        title: 'Cucumber Report'

    }
    var cucumberReporteroptions = {
        theme: 'bootstrap',
        jsonFile: jsonReports + '/cucumber_report.json',
        output: htmlReports + '/cucumber_reporter.html',
        reportSuiteAsScenarios: true
    };

    var JsonFormatter = Cucumber.Listener.JsonFormatter();
    JsonFormatter.log = function (string) {
        if (!fs.existsSync(jsonReports)) {
            fs.mkdirSync(jsonReports);
        }
        try {
            fs.writeFileSync(targetJson, string);
            reporter.generate(cucumberReporteroptions);  //invoke cucumber-html-reporter
            report.create(cucumberReportOptions).then(function () {  //invoke cucumber-html-report
            // creating two reports(optional) here, cucumber-html-report gives directory already exists as cucumber-html-reporter already creates the html dir!
            // suggestion- use either one of the reports based on your needs
                console.log('cucumber_report.html created successfully!');
            }).catch(function (err) {
                if (err) {
                    console.error(err);
                }
            });
        }
        catch (err) {
            if (err) {
                console.log('Failed to save cucumber test results to json file.');
                console.log(err);
            }
        }
    };
    this.registerListener(JsonFormatter);
}
module.exports = hooks;

reporter.js:

var reporter = require('cucumberjs-allure-reporter');
var fs = require('fs');
var xmlReports = process.cwd() + '/reports/xml';

var createXmlDir = function () {
    if (!fs.existsSync(xmlReports)) {
        fs.mkdir(xmlReports);
    }
} ();

reporter.config(
    {
        targetDir: './target/allure-results'
    }
);
module.exports = reporter;
Could you please help to sort it out.

**Comment by fdPoornima** [comment]
Hi, I have multiple xml files in allure-results since I am doing parallel execution. But in site folder, I am getting only one report. How can I get information about both the threads

**Comment by sarkershantonu** [comment]
@fdPoornima , can you share your pom.xml and the folder structure of generated reports site
