### ISSUE TITLE
Blank space in timeline

### ISSUE THREAD

**Issue by germaniteen** [allure-framework/allure-core#759]
Hi team,

Going through the timeline of allure report, there sometimes have blank spaces in timeline. Do you happen to let me know what this is about? As you can see at 33m20

Regards,
Tha`nh

![blankintimeline](https://cloud.githubusercontent.com/assets/7845001/13633190/13755336-e620-11e5-9a40-b464542688aa.png)

**Comment by vania-pooh** [comment]
@germaniteen 
1) I would recommend that you update Allure to 1.4.x or even 1.5.x series.
2) Allure XML files store start and end timestamps for each test case. You can check if there's a gap in these values. If so then this can be either a real pause in tests execution or an issue in adapter.

**Comment by baev** [comment]
@germaniteen what adaptor do you use?

**Comment by germaniteen** [comment]
Hi @baev, this is Cucumber.

**Comment by germaniteen** [comment]
@vania-pooh 

We're still using 1.4.x. Will follow up when upgrading to 1.5.x series

**Comment by baev** [comment]
I recommend to use 1.4.22 for now

**Comment by baev** [comment]
I recommend to use 1.4.22 for now

**Comment by germaniteen** [comment]
hi @vania-pooh,

Thanks for your recommendation. I think I found out the reason why. It is due to I do have duplicated scenarios. Once I removed one, the timeline is good for now.

**Comment by vania-pooh** [comment]
@germaniteen so this can be closed?

**Comment by germaniteen** [comment]
Sure @vania-pooh . Should allure do something instead of showing the blank like that? Just a suggestion. :)

**Comment by vania-pooh** [comment]
@germaniteen no it should not.
