### ISSUE TITLE
Screenshots in allure

### ISSUE THREAD

**Issue by anarwal** [allure-framework/allure-core#760]
I want to store my screenshots of defects in allure-report, I tried understanding it from allure-mocha project but dint reach far. I am using webdriver IO can someone suggest me a way to do that?

**Comment by just-boris** [comment]
What exactly do you want to get?

If you are using [mocha-allure-reporter](https://github.com/allure-framework/mocha-allure-reporter), you can make screenshots just calling `allure.createAttachement(screenshotName, content)`. Content should be something like `browser.takeScreenshot()`, it depends of your test framework

**Comment by baev** [comment]
closed as no response. Feel free to reopen
