### ISSUE TITLE
getting access denied error while trying to install allure CLI

### ISSUE THREAD

**Issue by PratPanig** [allure-framework/allure-core#761]

**Comment by just-boris** [comment]
Your report has not enough information to help you.
Which method are you using to install CLI? Homebrew? PPA? NPM? Anything else?
What operation do you have?

**Comment by PratPanig** [comment]
I tried using the homebrew method.

**Comment by baev** [comment]
I guess it is not an Allure issue. Try to run `brew doctor`, install using verbose mode and see the output.

**Comment by baev** [comment]
The issue like this: https://github.com/Homebrew/homebrew/issues/6814

**Comment by PratPanig** [comment]
I was able to generate the xml files. now how should i generate the html
file? pls help

**Comment by just-boris** [comment]
@PratPanig you can't open Allure in Safari or Chrome browsers just as html file. You should use `allure report open` command from the CLI.

See the following [FAQ section](https://github.com/allure-framework/allure-core/wiki/FAQ-and-Troubleshooting#i-see-nothing-when-opening-the-report-page-in-my-browser--access-denied-message)
