### ISSUE TITLE
Test case description of type 'html' is not supported

### ISSUE THREAD

**Issue by Bakanych** [allure-framework/allure-core#767]
I was trying to generate Allure report using allure-csharp-commons. For generated test cases with descriptiontype.html description text was escaped by parser.

![capture](https://cloud.githubusercontent.com/assets/17307409/14241946/0a14ef84-fa81-11e5-8d28-1ebfa7ba8ccb.PNG)

I found that testcase.html template supports only 'markdown' type:
```
<div class="testcase__description" text-cut="testcase.description.value" ng-show="testcase.description.value" escape-html="{{testcase.description.type.toLowerCase() != 'markdown'}}"></div>
```
but allure.xsd allows html also:
```
 <xs:simpleType name="description-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="markdown"/>
            <xs:enumeration value="text"/>
            <xs:enumeration value="html"/>
        </xs:restriction>
    </xs:simpleType>
```

**Comment by baev** [comment]
@Bakanych hi

Why did you need the `html` type of description? In feature releases we are planing to support only markdown type (you can use both `text` and `html` in markdown syntax).

**Comment by Bakanych** [comment]
@baev hi
I've already moved to markdown as I had too :) Not sure report generator supports it fully (i mean mixed markdown-html description). Anyway, now it works for me. Thanks!
