### ISSUE TITLE
How to run testng.xml suite with ru.yandex.qatools.allure.cucumberjvm.AllureRunListener

### ISSUE THREAD

**Issue by mmuntakim15** [allure-framework/allure-core#771]
Hi,

All of my cucumber test resides in testng.xml file which is being called on POM.xml configuration. It executes fine when i use ru.yandex.qatools.allure.testng.AllureRunListener but when i try to run with 
ru.yandex.qatools.allure.cucumberjvm.AllureRunListener it fails. below is the error message I am getting on my terminal.

Listener ru.yandex.qatools.allure.cucumberjvm.AllureRunListener@3d08f3f5 must be one of ITestListener, ISuiteListener, IReporter,  IAnnotationTransformer, IMethodInterceptor or IInvokedMethodListener
Usage: <main class> [options] The XML suite files to run
  Options:
    -configfailurepolicy
       Configuration failure policy (skip or continue)
    -d
       Output directory
    -dataproviderthreadcount
       Number of threads to use when running data providers
    -excludegroups
       Comma-separated list of group names to  exclude
    -groups
       Comma-separated list of group names to be run
    -junit
       JUnit mode
       Default: false
    -listener
       List of .class files or list of class names implementing ITestListener or
       ISuiteListener
    -methods
       Comma separated of test methods
       Default: []
    -methodselectors
       List of .class files or list of class names implementing IMethodSelector
    -mixed
       Mixed mode - autodetect the type of current test and run it with
       appropriate runner
       Default: false
    -objectfactory
       List of .class files or list of class names implementing
       ITestRunnerFactory
    -parallel
       Parallel mode (methods, tests or classes)
       Possible Values: [tests, methods, classes, instances, none, true, false]
    -port
       The port
    -reporter
       Extended configuration for custom report listener
    -suitename
       Default name of test suite, if not specified in suite definition file or
       source code
    -suitethreadpoolsize
       Size of the thread pool to use to run suites
       Default: 1
    -testclass
       The list of test classes
    -testjar
       A jar file containing the tests
    -testname
       Default name of test, if not specified in suitedefinition file or source
       code
    -testnames
       The list of test names to run
    -testrunfactory, -testRunFactory
       The factory used to create tests
    -threadcount
       Number of threads to use when running tests in parallel
    -usedefaultlisteners
       Whether to use the default listeners
       Default: true
    -log, -verbose
       Level of verbosity
    -xmlpathinjar
       The full path to the xml file inside the jar file (only valid if -testjar
       was specified)
       Default: testng.xml

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.638 s
[INFO] Finished at: 2016-04-08T13:23:28-04:00
[INFO] Final Memory: 32M/387M

**Comment by vania-pooh** [comment]
Summon @clicman

**Comment by clicman** [comment]
It because you trying to use cucumberJvmAdaptor with testNg. It is not possible because cucumberjvm.AllureRunListener depends on JUnit.

**Comment by mmuntakim15** [comment]
@clicman thanks for your reply.
