### ISSUE TITLE
[New face] JS console errors occur on report opening

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure-core#782]
Open any existing Jenkins [report](http://ci.qatools.ru/job/allure-core_pull-request/248/Allure_report/index.html) with opened dev tools.

Expected result: there're no console errors present.
Actual result: 2 console errors occur.

![errors](https://files.gitter.im/allure-framework/allure-core/SThW/blob)

Could be reproduced on local versions as well.

**Comment by baev** [comment]
fixed in Allure 2

**Comment by just-boris** [comment]
This is probably related with #809
@baev, did you fix that?
