### ISSUE TITLE
[New face] Some Overview / Defects dashboards' info is uninformative

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure-core#785]
1) Run any test.
2) Generate report via maven plugin.
3) Drill into report's results and navigate to `Overview / Defects` tabs.

Expected result: all labels are informative and straightforward.
Actual result: some labels reflect not quite obvious info (pretty similar to debug messages).

![image](https://cloud.githubusercontent.com/assets/6638780/14588436/85a3207a-04d2-11e6-9468-8c0ccc6839e3.png)

![image](https://cloud.githubusercontent.com/assets/6638780/14588447/b1fd2710-04d2-11e6-96d3-d90d5f46b02a.png)

**Comment by baev** [comment]
@sskorol thanks for the report

**Comment by baev** [comment]
fixed in Allure 2
