### ISSUE TITLE
How to add Severity level to AllureCucumberJVM plugin? 

### ISSUE THREAD

**Issue by mmuntakim15** [allure-framework/allure-core#786]
Is it possible to add Severity level to AllureCucumberJVM plugin. 

For example: when I use the severity annotation before testng @Test annotation, it displays correctly on the report but when I use it before cucumber annotation @Given, it does not display correct severity level on the report, Instead it just displays severity as Normal by default.

    @Severity(SeverityLevel.BLOCKER)
    @Given("^mySampleTest$")
    public void sampleTest() {
      //Some Actions 
    }

This is not a big issue for our test, but just wondering if this supported for cucumber plugin, Or maybe I'm not placing the annotation on correct place.

Thanks,

**Comment by vania-pooh** [comment]
@mmuntakim15 please reopen in https://github.com/allure-framework/allure-cucumber-jvm-adaptor/issues/
