### ISSUE TITLE
allure setup for linux redhat distrubution

### ISSUE THREAD

**Issue by DeChrish** [allure-framework/allure-core#792]
We are able to install allure, but no documentation to export the allure path. we tried to add /bin/allure to ALLURE_CONFIG, but it fails

**Comment by vania-pooh** [comment]
@DeChrish could please specify the following:
1) Which tool are you installing: command-line client or a plugin for some CI tool?
2) Why do you need to export Allure path?

**Comment by DeChrish** [comment]
@vania-pooh 

1 - command-line client in enterprise linux
