### ISSUE TITLE
[RU] Вечная загрузка отчета

### ISSUE THREAD

**Issue by Kappasama** [allure-framework/allure-core#793]
При попытке открыть сгенерированный отчет на локальной машине вечно показывается надпись "Loading..."

allure-commandline 1.4.23
pytest-allure-adaptor - 1.7.2
chrome Версия 50.0.2661.87 m

В консоле хрома ошибка:
`jquery.min.js:4 XMLHttpRequest cannot load file:///D:/rep/data/plugins.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.k.cors.a.crossDomain.send @ jquery.min.js:4`

**Comment by allustin** [comment]
@Kappasama насколько я понял - такое поведение только если открыть index.html локально
если использовать `allure report open` то все работает

**Comment by vania-pooh** [comment]
http://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome/24002146#24002146

**Comment by sskorol** [comment]
Из `IntelliJ IDEA` можно и напрямую `index.html` открывать без всяких доп. серверов.
