### ISSUE TITLE
Will there be a pre-release / release of new allure soon? 

### ISSUE THREAD

**Issue by tk8817** [allure-framework/allure-core#797]
Hey, 
Some great commits have been sitting in master that I would love to utilize in my build plans.

Mainly
1) support for video files embedded in report
2) new interface

Any chance you can comment on when a pre-release or release may occur. Thank you so much for all the great work!

**Comment by vania-pooh** [comment]
@tk8817 we have a week of country-wide vacation right now so core developers are not available right now. Let's return to this question on the next week.

**Comment by sskorol** [comment]
@tk8817 you can build latest snapshot by your own. :) I'm using it for 2 weeks, seems great.

**Comment by tk8817** [comment]
any update here?

**Comment by vania-pooh** [comment]
@baev please comment on this...

**Comment by baev** [comment]
1.4.24.RC1 was released

**Comment by tk8817** [comment]
Woooooooo! You guys rock. My Bamboo installation thanks you.
