### ISSUE TITLE
DSL option for Allure Reports

### ISSUE THREAD

**Issue by DeChrish** [allure-framework/allure-core#798]
Currently we are using DSL jobs to create Jenkins jobs, how to add Allure Steps in the below dsl job?
Ex : 

job ("demo test"){
 ....
  scm {
    git gitURI, 'master', { node ->
      node / 'extensions' << 'hudson.plugins.git.extensions.impl.CleanCheckout'()
    }
  }

  authorization {
    permission('hudson.model.Item.Build', 'anonymous')
  }
  
  triggers {
    cron 'H * * * *'
  }
  
  steps {
    shell '''
      export PATH="\$PATH:\$(npm bin)"
      npm install
      rm -Rf allure-results*
      rm -Rf allure-reports*
 '''
}

publishers {
    archiveArtifacts 'target/**/screenshots/,target/**/test-results.txt,target/**/coverage.json'
    mailer '', true, true
  }
}

**Comment by baev** [comment]
Have you seen http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-jobdslplugin ?

**Comment by DeChrish** [comment]
@baev 
Thanks
