### ISSUE TITLE
Allure report 1.4.23: docstrings (test case description) displays incorrectly

### ISSUE THREAD

**Issue by ex3me0** [allure-framework/allure-core#800]
> pytest-allure-adaptor == 1.7.2
> allure commandline verison == 1.4.23
> Firefox/Chrome == latest

In my **python code docstrings** are written like that:
```
    """
    Assert on:
        status code == 200
        response from server is JSON
        json response object contains attributes: 'iid', 'sub_site_id'
        'iid', 'sub_site_id' is digits
    """
```
In the **testsuite.xml**, generated by adaptor:

```
      <description>
    Assert on:
        status code == 200
        response from server is JSON
        json response object contains attributes: 'iid', 'sub_site_id'
        'iid', 'sub_site_id' is digits
    </description>
```
In the **testcase.json** generated by allure commandline (here we can see line wrapping and "space layout"):

```
  "description" : {
    "value" : "\n    Assert on:\n        status code == 200\n        response from server is JSON\n        json response object contains attributes: 'iid', 'sub_site_id'\n        'iid', 'sub_site_id' is digits\n    ",
    "type" : "TEXT"
  }
```

But browser displays description without the line wrapping and "space layout": http://i.imgur.com/LPeF5CN.png

Also I want to say that the description of the test cases would be easier to see in the expanded form (with the possibility of collapse)

**Comment by ex3me0** [comment]
Temporarily for myself solved by this way:
`<pre> {{test case.description.value}} </ pre>`
(templates\testcase\testcase.html 46 line)

But this not the best way I think)

**Comment by baev** [comment]
@ex3me0 hi! Sorry for the delay! I'll take a look

**Comment by baev** [comment]
closed as duplicate https://github.com/allure-framework/allure-core/issues/690
