### ISSUE TITLE
Not able to generate report for xUnit Test

### ISSUE THREAD

**Issue by arpit-nagar** [allure-framework/allure-core#805]
Hi, 

I want to create allure reports for xUnit Test. But could not able to generate.
Is allure capable to create xUnit Tests report?

[test-report.txt](https://github.com/allure-framework/allure-core/files/272782/test-report.txt)

**Comment by baev** [comment]
@arpit-nagar Hi

Allure doesn't support xUnit Test.

**Comment by arpit-nagar** [comment]
Are there any plans to support xUnit xml ??

**Comment by baev** [comment]
Yep, Allure 2 already supports xUnit format

**Comment by arpit-nagar** [comment]
Do you have any ETA for Allure 2 release. 
I can see a lot of commits happening in Allure2. But can not able to use it or see any sample report.

**Comment by baev** [comment]
> Do you have any ETA for Allure 2 release.

The report is almost done, you can try it out. I guess we will finish all the work in next few weeks, but then we need to update all the integrations to support new features. 

Our report sample available here https://qameta.io/allure/demo/
[Here you can find latest available command line](https://bintray.com/qameta/generic/allure2)

**Comment by arpit-nagar** [comment]
Can you please suggest how to generate Allure report for xUnit xml  [[test-report.txt](https://github.com/allure-framework/allure-core/files/272782/test-report.txt)] from Allure 2.

**Comment by baev** [comment]
you need to install latest allure commandline https://docs.qameta.io/allure/2.0/#_installing_a_commandline , then simply generate the report using `$ allure generate /path/to/directory/with/xunit/results` command

**Comment by Pardol** [comment]
Thank you for quick response! It seems my problem was in the naming.  Directory that contains allure results has to be named "allure-results" otherwise xunit-xml results will not be found.
