### ISSUE TITLE
Incorrect test run start date in report in report overview 

### ISSUE THREAD

**Issue by Bakanych** [allure-framework/allure-core#812]
Hi all,
I found that start date is shown incorrectly in version 1.4.24.
1.4.23:
![capture](https://cloud.githubusercontent.com/assets/17307409/15734305/d6ad0712-28c0-11e6-8fd3-1654b695ccd0.PNG)

1.4.24:
![capture](https://cloud.githubusercontent.com/assets/17307409/15734297/b5d28788-28c0-11e6-9b76-20333315636a.PNG)

test suite xml used:
`<test-suite xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:model.allure.qatools.yandex.ru" start="1464840970825" stop="1464841010050"`

**Comment by just-boris** [comment]
Thanks for report!

I confirm the issue, will look at it.
