### ISSUE TITLE
Your report seems to be broken

### ISSUE THREAD

**Issue by arpit-nagar** [allure-framework/allure-core#817]
Hi,
I am getting error 
```
Your report seems to be broken! Check out our FAQ to find a reason
Message:
Debug:
```
It is still showing report but with above pop-up.
What I am doing wrong??
![capture](https://cloud.githubusercontent.com/assets/16220515/15837815/739dfeec-2c58-11e6-9104-e39688d7524d.JPG)

**Comment by baev** [comment]
@arpit-nagar hi! Could you please provide more information? What browser did you use, OS? It is Jenkins am I right?

**Comment by arpit-nagar** [comment]
@baev 
Yes, I am using Jenkins and OS is Windows.
I am executing .net testcases in jenkins and using [MSTestAdapter](https://github.com/allure-framework/allure-mstest-adapter) to convert trx file to allure reports.
I tested it at chrome and mozilla and both is giving same error.
I am attaching some screenshot, trx and allure reports.
Please let me know if you need more info.

[Download allure and trx](https://drive.google.com/file/d/0B_sY96SGLXduTXpvNUVyTTVUVFk/view?usp=sharing)


![1](https://cloud.githubusercontent.com/assets/16220515/15848760/7e82203c-2cac-11e6-9fd4-a77949bcf914.JPG)
![2](https://cloud.githubusercontent.com/assets/16220515/15848761/7e83a27c-2cac-11e6-9951-7857d814cf33.JPG)
![3](https://cloud.githubusercontent.com/assets/16220515/15848762/7e903b22-2cac-11e6-9b06-db5daffcbb53.JPG)
![4](https://cloud.githubusercontent.com/assets/16220515/15848763/7e9365ae-2cac-11e6-89a6-5e098471f036.JPG)
![5](https://cloud.githubusercontent.com/assets/16220515/15848764/7e93feec-2cac-11e6-8c45-800ff7ea2a68.JPG)

**Comment by just-boris** [comment]
This is CSP bug https://github.com/allure-framework/allure-core/issues/715

See instructions in Jenkins plugin documentation: http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-configure-security

You need to setup this to make Allure work in latest Jenkins version.

**Comment by arpit-nagar** [comment]
Thanks @just-boris :+1:
