### ISSUE TITLE
allure.properties does not get picked up in v1.24.RC1/2

### ISSUE THREAD

**Issue by tk8817** [allure-framework/allure-core#819]
Hey, 

I noticed my allure.properties is not working in the new release versions RC1 & RC2, was working fine in 1.23. I am using allure_cucumber as my adapter.

Example of my file
```
allure.issues.tracker.pattern=https://test.atlassian.net/browse/%s
allure.tests.management.pattern=https://test.atlassian.net/browse/%s
```

**Comment by tk8817** [comment]
@baev - any thoughts on this?

**Comment by tk8817** [comment]
feeling very lonely here, is everyone at Yandex alive and well :)

**Comment by vania-pooh** [comment]
@tk8817 sorry for these delays. Will try to kick someone of the team who is aware of this new stuff.

**Comment by baev** [comment]
@tk8817 hi! Sorry for the delay. Could you please provide a sample project to reproduce the problem?

**Comment by tk8817** [comment]
Hi folks, this is actually a mistake on my side it would appear. Using Allure inside of docker and the allure report generate was being called in a different location that the allure.properties. 

Closing.
