### ISSUE TITLE
Jenkins plugin: Report loading 

### ISSUE THREAD

**Issue by shynkevich-alex** [allure-framework/allure-core#820]
Hello, I have configured Allure Jenkins plugin and Allure command line tool.
And it seems generates reports but when I opens it I just see "Loading".

We use Jenkins v.2.8, Allure plugin 2.10

**Comment by baev** [comment]
Hi! 
See http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-configure-security

**Comment by shynkevich-alex** [comment]
Hi, thanks. It works.

**Comment by just-boris** [comment]
I'd like to put a reference to #715 to see how much users are confused by changes in Jenkins policy.
