### ISSUE TITLE
using allure with testNG programatically

### ISSUE THREAD

**Issue by gedaiu** [allure-framework/allure-core#822]
Hi,

I want to create a simple custom testNg runner, like this:

```
        List<String> suites = Lists.newArrayList();
        suites.add(path);

        testng.setTestSuites(suites);
        testng.addListener(new AllureTestListener());

        testng.run();
```

and no allure xml is written after the test are run.

**Comment by baev** [comment]
Hi @gedaiu ! Thanks for the report! All works file for me. What version of TestNg do you use? Also I have to cast AllureTestListener to Object to make it work:

```java
testng.addListener((Object) new AllureTestListener());
``` 

Could you please provide a sample project to reproduce the problem?

**Comment by gedaiu** [comment]
it works.. . properly now... I forgot to start the weaver.

Thanks!

**Comment by MartinKeprta** [comment]
I have exactly same issue. I generated around 60 test suites and i want assign Allure Listener to testNG runner... How to do it?
