### ISSUE TITLE
Test name is displayed instead of a title in the tests' lists table

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure-core#825]
Version: 1.4.24.RC2

1) Annotate test case with `@Title`.
2) Run it and generate report.

Expected result: title is displayed both in test cases' table and corresponding test details.

Actual result: test cases' table contains test name instead of a title (see attachments).

![image](https://cloud.githubusercontent.com/assets/6638780/16516205/5e37a5d2-3f7f-11e6-9aec-984e7e4debb7.png)

![image](https://cloud.githubusercontent.com/assets/6638780/16516190/43b9de5a-3f7f-11e6-956c-600126fd5804.png)

![image](https://cloud.githubusercontent.com/assets/6638780/16516174/2968d9e8-3f7f-11e6-95a3-b2ba6487d5f4.png)

**Comment by sskorol** [comment]
FYI, checking it. I think I know how to fix that.

**Comment by just-boris** [comment]
This is likely question for @baev how it should be by design.

Maybe this was intentional

**Comment by sskorol** [comment]
@just-boris in 1.4.23 version it was displayed correctly. Similar issue https://github.com/allure-framework/allure-core/pull/781 was raised before and fixed by you btw. :)

**Comment by sskorol** [comment]
Fixed, closing.
