### ISSUE TITLE
How to add Allure reports test Numbers  to Jenkins Dashboard View 

### ISSUE THREAD

**Issue by DeChrish** [allure-framework/allure-core#828]
Job  ↓ sample-job-test
Success #   1
%   
Failed #  1 
%   
Skipped #  2  
%   
Total #   4

Dashboard View : https://wiki.jenkins-ci.org/display/JENKINS/Dashboard+View

**Comment by DeChrish** [comment]
@Boris Serdiuk any help?

**Comment by DeChrish** [comment]
@just-boris any help?

**Comment by just-boris** [comment]
Hello! 
This is very Jenkins-specific feature. It shouldn't belong to core project. Please open the issue in [allure-jenkins](https://github.com/jenkinsci/allure-plugin) project.
