### ISSUE TITLE
Unable to attach video file using py.test adapter

### ISSUE THREAD

**Issue by OlehKuzovkov** [allure-framework/allure-core#829]
For some reasons the video file cannot be attached.

I am using:
```
class AttachmentTypeExtended(Enum):

    def __init__(self, mime_type, extension):
        self.mime_type = mime_type
        self.extension = extension

    MP4 = ("video/mp4", "mp4")

allure.attach("video_test", video_file, AttachmentTypeExtended.MP4)
```

From the original size of 200kb only 20 byte file is displayed in the attachment witch does not work (obviously).

Maybe I am doing something wrong?

**Comment by OlehKuzovkov** [comment]
I have found that you cannot just pass the file path into allure.attach, you have to read it and pass like a byte array.

It would be great to have such description in the User guide :)

**Comment by SergeyPirogov** [comment]
@OlehKuzovkov could you please share your experince about video attachment? Have you able to play video inside report?

**Comment by OlehKuzovkov** [comment]
Yes, Of course.

What problems you are experiencing ?

**Comment by SergeyPirogov** [comment]
@OlehKuzovkov I faced with problem - video is attached to report, but I not able to play it inside report. When I click on video attachment it downloads video first. Do you have skype? Let's chat a bit

**Comment by SergeyPirogov** [comment]
@OlehKuzovkov I want to achieve something like in java. See example https://www.youtube.com/watch?v=74zD5q9DKTw

**Comment by OlehKuzovkov** [comment]
My skype is oleg_rada.
