### ISSUE TITLE
php api doesn't have such annotation as TestCaseID

### ISSUE THREAD

**Issue by Gordiievskyi** [allure-framework/allure-core#833]
Hi guys,

Please add such Annotation type to allure-php-adapter-api(not php unit adapter) as java api has
ru.yandex.qatools.allure.annotations.TestCaseId

**Comment by just-boris** [comment]
Hello, feature requests about PHP implementation should be reported in appropriate repository: https://github.com/allure-framework/allure-php-adapter-api

Also, if you have request for some specific framework, there are following repositories:

* [Codeception](https://github.com/allure-framework/allure-codeception)
* [PHPUnit](https://github.com/allure-framework/allure-phpunit)

**Comment by Gordiievskyi** [comment]
sorry for that, please close my issue
