### ISSUE TITLE
NumberFormatException for input ""

### ISSUE THREAD

**Issue by mDomingues** [allure-framework/allure-core#834]
Hi guys,

I'm problems using version **1.4.24.RC2** with this kind of error.
StackTrace:
![screen shot 2016-07-15 at 11 47 32](https://cloud.githubusercontent.com/assets/11029958/16872007/0d48e8a8-4a82-11e6-8b9d-b3db0a9025b0.png)

With this kind of errors they shouldn't affect the report generation, just the file parse itself.

**Comment by sskorol** [comment]
@mDomingues steps to reproduce?

**Comment by mDomingues** [comment]
Well my suite has tests for everything, since opening dropdowns, click on elements helpers, click on charts options, elements visibility,... 
Running through these tests, somehow is causing that. Here you have the output of allure from **wdio**.

[allure_debug.zip](https://github.com/allure-framework/allure-core/files/365860/allure_debug.zip)

**Comment by just-boris** [comment]
Hello!

@mDomingues likely you got this issue: https://github.com/webdriverio/wdio-allure-reporter/issues/24 There is no workaround for now, but I am working on it. Subscribe on that issue to track progress.

I will close this issue as not related to the core project.
