### ISSUE TITLE
Show full text of step when hovering

### ISSUE THREAD

**Issue by marty30** [allure-framework/allure-core#838]
For each Step that is too long, it is being wrapped. But there is no way to view the full text. A tooltip (using the title attribute) could be a solution to this problem.

**Comment by sskorol** [comment]
`-Dallure.max.title.length=N` will resolve your issue.

**Comment by marty30** [comment]
It will not completely resolve my issue, but it is a quick fix ;)

**Comment by danieldatri** [comment]
+1

**Comment by PavelSusloparovNYT** [comment]
Nice! Thank you!
