### ISSUE TITLE
All tests which were not executed were marked as skipped in allure-cucumber-jvm-adaptor

### ISSUE THREAD

**Issue by mmuntakim15** [allure-framework/allure-core#841]
In allure cucumber-jvm plugin report displays all skipped tests as "Pending", instead two different groups: pending and canceled tests.

Is this a bug? or do I have to change anything on my POM.XML to make it work?

**Comment by baev** [comment]
cucumber-jvm is supported by the community. Could you please create the issue in related repository? https://github.com/allure-framework/allure-cucumber-jvm-adaptor
