### ISSUE TITLE
Duration time for Cucumber Test Scenario displays as "0"

### ISSUE THREAD

**Issue by mmuntakim15** [allure-framework/allure-core#842]
Hello, 

Any help for below issue is highly appreciated.

Total duration time for individual test scenario is not being calculated correctly. For example if I have three test steps where each steps took 1 Second then Scenario duration time should display duration as 3 Second. Please see the attached screenshot for further details. 

Again any help will be appreciated. 
Thanks
![durationerror](https://cloud.githubusercontent.com/assets/11964005/17486793/2802de6a-5d60-11e6-9f23-fb130e4988bd.png)

**Comment by baev** [comment]
@mmuntakim15 hi! Sorry for the delay. Could you please report the issue to related adaptor repository?
