### ISSUE TITLE
[RU] gradle + allure + cucumber-jvm

### ISSUE THREAD

**Issue by jalona** [allure-framework/allure-core#847]
Привет всем.

В maven это делается через surefire с указанием CustomAllureRunListener  и подтягиванием 
```
<includes>
     <include>**/*AT.java</include>
</includes>
```
Имеется ли возможность реализовать запуск тестов в связке
gradle + allure + cucumber-jvm ?

**Comment by vania-pooh** [comment]
А можно попросить тикет перенести в репозиторий cucumber-jvm?

**Comment by jalona** [comment]
@vania-pooh сюда [allure-cucumber-jvm-adaptor] (https://github.com/allure-framework/allure-cucumber-jvm-adaptor) ?

**Comment by vania-pooh** [comment]
Да.

**Comment by jalona** [comment]
https://github.com/allure-framework/allure-cucumber-jvm-adaptor/issues/31
