### ISSUE TITLE
Unable to auto-push newly generating scripts in the custom folder

### ISSUE THREAD

**Issue by prashanth-sams** [allure-framework/allure-core#849]
Instead of `custom-folder`, the json data is still populated under `allure-results`

```
onPrepare: function () {
    var AllureReporter = require('jasmine-allure-reporter');
    jasmine.getEnv().addReporter(new AllureReporter({
          allureReport : {
              resultsDir : 'custom-folder'
          }
      }));
};
```

**Comment by baev** [comment]
Hi! 
Could you please move the issue to https://github.com/allure-framework/allure-jasmine-plugin

**Comment by prashanth-sams** [comment]
@baev I tried the way given in ttps://github.com/allure-framework/allure-jasmine-plugin
Anything I missed out?
