### ISSUE TITLE
How to use the annotations @Issue, @TestCaseID, etc with Cucumber-JVM framework ?

### ISSUE THREAD

**Issue by ankit-ojha** [allure-framework/allure-core#852]
I tried adding the way it is mentioned in the documentations but i was not able to see the Test Case ID and Issue ID.

Sample Code :

@Issue("CON-1062")
	@When("^User logs in using Username as \"(.*)\" and Password \"(.*)\"$")
	public void login(String username, String password) {
		-- implementation code
	}
@TestCaseId("CON-1055")
	@Then("^User should be logged in$")
	public void User_should_be_logged_in() throws Throwable {
                   -- implementation code

}

How can we integrate these things with [Cucumber JVM Framework](https://github.com/allure-examples/allure-cucumber-jvm-example) ? 

Using the [documentation](https://github.com/allure-framework/allure-core/wiki/Issues) and other framework (Like TestNG), I was able to see those linkable IDs in the report. Is there a way to use these annotations with Cucumber JVM Framework ?

**Comment by vania-pooh** [comment]
Please move to https://github.com/allure-framework/allure-cucumber-jvm-adaptor/issues/.
