### ISSUE TITLE
Incorrect step name parse

### ISSUE THREAD

**Issue by Bakanych** [allure-framework/allure-core#854]
I have the following step in xml suite:
`        <step start="1473223889754" stop="1473223889831" status="passed">
          <name>When I update @custom with data expecting error 'Error occured: Sorry...'</name>
        </step>`

Result step name in Allure report looks like this:
![image](https://cloud.githubusercontent.com/assets/17307409/18300985/63041ec2-7500-11e6-947a-27a5ce35038f.png)

**Comment by baev** [comment]
@Bakanych the problem is that you suppose to use `title` instead of `name`. What adaptor did you use?

**Comment by Bakanych** [comment]
I'm using custom adapter for specflow based on [allure-csharp-commons](https://github.com/allure-framework/allure-csharp-commons).
Will check my code also.
Thanks!

**Comment by Bakanych** [comment]
@baev I've fixed my code. Thanks again!
Please close this issue.
