### ISSUE TITLE
Is there any way to add company logo instead of allure logo?

### ISSUE THREAD

**Issue by pthewizard** [allure-framework/allure-core#864]

**Comment by baev** [comment]
Hi! Yes, you can. 

You need to [implement a report plugin](https://github.com/baev/allure-report-plugins). But imho there is no reason to implement it for 1.4.* because 2.0 is coming soon (and plugin api is broken in 1.4.24.RC*)

**Comment by RocketRaccoon** [comment]
Any concrete dates about 2.0 version?

**Comment by baev** [comment]
You can try out a first beta release https://github.com/allurefw/allure-report/releases/tag/2.0-BETA1

An example plugin to change the logo: https://github.com/allurefw/allure-report/tree/master/plugins/custom-logo-plugin

**Comment by benzhou2014** [comment]
Is there a place to modify the logo title as well?
