### ISSUE TITLE
New feature: It would be great to have server reporting where one can get to see previous test run history

### ISSUE THREAD

**Issue by pthewizard** [allure-framework/allure-core#866]

**Comment by vania-pooh** [comment]
@pthewizard that's a known issue. We're working on it.

**Comment by just-boris** [comment]
@vania-pooh would be nice to link this with previous discussions or some announcements.
I couldn't find any so far.

**Comment by baev** [comment]
@just-boris agree. As far as I know there are no announcements yet. 

BTW Allure Server is closed alpha for now, so stay turned

**Comment by prasanta-biswas** [comment]
any specific date for the release?
