### ISSUE TITLE
Stack trace section could be more readable

### ISSUE THREAD

**Issue by pr4bh4sh** [allure-framework/allure-core#868]
IMO just some CSS improvement. previous was more readable/pleasant.
with version 1.4.24.RC2
![image](https://cloud.githubusercontent.com/assets/6311526/19440271/eedbee30-949e-11e6-8563-dcd932825bfa.png)

with version  1.4.23
![image](https://cloud.githubusercontent.com/assets/6311526/19440306/132ab08c-949f-11e6-9017-903ac1be5ee5.png)

**Comment by just-boris** [comment]
The situation on your  screenshot is not expected. For me it looks better:

![image](https://cloud.githubusercontent.com/assets/812240/19440717/359f2f60-9483-11e6-80bc-aa0d7f6dedb7.png)

Any information about your browser version and OS would be helpful.

**Comment by pr4bh4sh** [comment]
Yes, the issue seems to be with the browser. Checked with firefox on the same machine it does not happen on firefox.

Here's the detail where issue is faced
Browser : Google Chrome Version 53.0.2785.101 (64-bit)
OS : Ubuntu 15.10

**Comment by baev** [comment]
Fixed in 2.0-BETA1 https://github.com/allurefw/allure-report/releases/tag/2.0-BETA1

![screen shot 2016-11-02 at 17 33 21](https://cloud.githubusercontent.com/assets/2149631/19932838/8032b7b2-a122-11e6-9f81-875621a7b3d0.png)
