### ISSUE TITLE
Unable to use default zoom on custom html attachments

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure-core#869]
Allure: 1.4.24.RC3

Steps:
 - Attach the following html to any valid testcase:

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../styles.css">
</head>
<body>
    <div class="pane__section attachment__media-container">
        <video class="attachment__media" controls>
            <source src="{{link}}" type="video/mp4">
            Your browser does not support video tag
        </video>
    </div>
</body>
</html>
```
Where `{{link}}` is any valid mp4 video url.
 - Generate html report and open attachment.
 - Hover over video recording, until zoom icon appeared.

![image](https://cloud.githubusercontent.com/assets/6638780/19523299/c0c17b48-9622-11e6-9103-3071b85104e5.png)

 - Click video.

Expected result: video has been resized.
Actual result: nothing happened.

Note that zoom works fine for any common attachment (screenshots / video) or if we click the following icon:
![image](https://cloud.githubusercontent.com/assets/6638780/19523356/eb43bd86-9622-11e6-8764-38ac610c7a41.png)

**Comment by just-boris** [comment]
First of all, our stylesheet is not a part of public API.
You can include it on your custom page, but it is not guaranteed that there will be no breaking changes.

Video resize in Allure happens with Javascript. Add our CSS will be not enough to make this work.

**Comment by sskorol** [comment]
@just-boris so what would you suggest to make zoom working for custom html attachments?

**Comment by just-boris** [comment]
So far, Allure UI just adds an extra class on click to block and removes it on click again. This extra class enlarges the size of wrapping block.

But this is a very common question how to do it with CSS, you can find more answers [somewhere else](http://stackoverflow.com/). Allure doesn't have any constraints for your attachment, html is displayed to fill all available place on the screen.
