### ISSUE TITLE
how to build report in java application?

### ISSUE THREAD

**Issue by walbx** [allure-framework/allure-core#872]
Hi,

I wonder if there is way to build report just in java application, without using any "Report Generation Tools"?

I tried to use allure-report-builder by imitating the testcase "AllureReportBuilderTest",  but when the use case runs into "processResultsTest", the program is stuck and there is no exception.

**Comment by baev** [comment]
I guess you can use [AllureReportGenerator](https://github.com/allure-framework/allure-core/blob/master/allure-report-data/src/main/java/ru/yandex/qatools/allure/data/AllureReportGenerator.java)

But in that case you need to control your classpath for plugins loading, manually set configuration properties, and this is not a part of public API, so it can be changed in any moment.

**Comment by walbx** [comment]
Thanks for your reply.
I simply tried to use AllureReportGenerator ,calling code is as following:
```
        File input = new File(xmlResultsFilePath);
        File output = new File(Path2StoreReport);
        AllureReportGenerator generator = new AllureReportGenerator(input);
        generator.generate(output);
````
Then I got two folders named "data" and "plugins"，the "data" folder have some .json data like "total.json", "xnuit.json", etc. 

But the comment of latest commit say "write index.html", that is the result of what I expect (full report that can be view in the browser)

Would you please give any further assistance?

**Comment by walbx** [comment]
Thanks for your suggestion.
