### ISSUE TITLE
Dynamic test name

### ISSUE THREAD

**Issue by tnimni** [allure-framework/allure-core#882]
Hi,

I have a test that basically compare 2 items, I have to compare a lot of items.
In order to do it nicely I created a Junit test and I'm running it with Parametrized.class
Now I wish to control the name of the test in the report according to the actual parameters being sent.

Is that possible?

**Comment by baev** [comment]
@tnimni hi, sorry for the delay. 

Yes, you can change test case name using `Allure.LIFECYCLE`. You need to implement your own [TestCaseEvent](https://github.com/allure-framework/allure-core/blob/master/allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/events/TestCaseEvent.java) and then use it in test case:

```java
Allure.LIFECYCLE.fire(new ChangeTestCaseNameEvent(parameters)); 
```

**Comment by tnimni** [comment]
Hi,
Thank you for the response, I found another way meanwhile using this annotation above the parameters
@Parameters(name= "budget: {0} report: {1}")
and removing @Title annotation from the test case, it has it's own limitations but it works :)
