### ISSUE TITLE
Can't add red icon or any text in step

### ISSUE THREAD

**Issue by RomanIovlev** [allure-framework/allure-core#982]
How to write message in Allure from code (not via annotation)?
Please reopen https://github.com/allure-framework/allure1/issues/967
The code in answer not work in latest versions

**Comment by baev** [comment]
> The code in answer not work in latest versions

If you mean Allure v2 the answer is yes, some method signatures was changed. Allure the repository is changed as well.

https://github.com/allure-framework/allure2 - report generator
https://github.com/allure-framework/allure-java - java integrations

PS the correct code is 

```java
public void log(String message, Status status) {
    String uuid = UUID.randomUUID().toString();
    StepResult result = new StepResult().withName(message).withStatus(status);
    Allure.getLifecycle().startStep(uuid, result);
    Allure.getLifecycle().stopStep(uuid);
}
```
